INSERT INTO `persons`( `name`)VALUES ("Абросимов П. П.");
INSERT INTO `persons`( `name`)VALUES ("Авзотис Г.");
INSERT INTO `persons`( `name`)VALUES ("Аглицкий Г. А.");
INSERT INTO `persons`( `name`)VALUES ("Агню Д.");
INSERT INTO `persons`( `name`)VALUES ("Адамович С. М.");
INSERT INTO `persons`( `name`)VALUES ("Александров");
INSERT INTO `persons`( `name`)VALUES ("Алешин");
INSERT INTO `persons`( `name`)VALUES ("Алешина А. Б.");
INSERT INTO `persons`( `name`)VALUES ("Альперович Б. С.");
INSERT INTO `persons`( `name`)VALUES ("Альшванг А. А.");
INSERT INTO `persons`( `name`)VALUES ("Андреев Н.");
INSERT INTO `persons`( `name`)VALUES ("Андреев С.");
INSERT INTO `persons`( `name`)VALUES ("Андреева Н.");
INSERT INTO `persons`( `name`)VALUES ("Андрианов Н. Н.");
INSERT INTO `persons`( `name`)VALUES ("Антоновский");
INSERT INTO `persons`( `name`)VALUES ("Аргатов И. И.");
INSERT INTO `persons`( `name`)VALUES ("Аркадий (Федоров)");
INSERT INTO `persons`( `name`)VALUES ("Арсеньев Ю. К.");
INSERT INTO `persons`( `name`)VALUES ("Архипова П. Е.");
INSERT INTO `persons`( `name`)VALUES ("Афанасьев А. А.");
INSERT INTO `persons`( `name`)VALUES ("Базегский П. И.");
INSERT INTO `persons`( `name`)VALUES ("Байков Ф.");
INSERT INTO `persons`( `name`)VALUES ("Бакланов Ю. П.");
INSERT INTO `persons`( `name`)VALUES ("Баландин Т. В.");
INSERT INTO `persons`( `name`)VALUES ("Баралл П.");
INSERT INTO `persons`( `name`)VALUES ("Баранов Д. О.");
INSERT INTO `persons`( `name`)VALUES ("Баранцов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Барбашин В. Б.");
INSERT INTO `persons`( `name`)VALUES ("Басинский");
INSERT INTO `persons`( `name`)VALUES ("Башев П. А.");
INSERT INTO `persons`( `name`)VALUES ("Башева А. М.");
INSERT INTO `persons`( `name`)VALUES ("Белиловский К. А.");
INSERT INTO `persons`( `name`)VALUES ("Беляев А. П.");
INSERT INTO `persons`( `name`)VALUES ("Беляев И. С.");
INSERT INTO `persons`( `name`)VALUES ("Беляков С. М.");
INSERT INTO `persons`( `name`)VALUES ("Бенкендорф А. Х.");
INSERT INTO `persons`( `name`)VALUES ("Березин");
INSERT INTO `persons`( `name`)VALUES ("Бесов");
INSERT INTO `persons`( `name`)VALUES ("Беспальчев А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Благородченков");
INSERT INTO `persons`( `name`)VALUES ("Блау");
INSERT INTO `persons`( `name`)VALUES ("Блок А. А.");
INSERT INTO `persons`( `name`)VALUES ("Бобринский А. А.");
INSERT INTO `persons`( `name`)VALUES ("Богданов В.");
INSERT INTO `persons`( `name`)VALUES ("Богданов В. Н.");
INSERT INTO `persons`( `name`)VALUES ("Богданов М.");
INSERT INTO `persons`( `name`)VALUES ("Богданов П.");
INSERT INTO `persons`( `name`)VALUES ("Болотников И. М.");
INSERT INTO `persons`( `name`)VALUES ("Большаков И. П.");
INSERT INTO `persons`( `name`)VALUES ("Бонбин П.");
INSERT INTO `persons`( `name`)VALUES ("Бржеский В. Ч.");
INSERT INTO `persons`( `name`)VALUES ("Бронштейн А. Л.");
INSERT INTO `persons`( `name`)VALUES ("Вавилов Г. А.");
INSERT INTO `persons`( `name`)VALUES ("Вагнер");
INSERT INTO `persons`( `name`)VALUES ("Валентик И. Я.");
INSERT INTO `persons`( `name`)VALUES ("Варзугин Н. П.");
INSERT INTO `persons`( `name`)VALUES ("Вашингтон Д.");
INSERT INTO `persons`( `name`)VALUES ("Введенский А. И.");
INSERT INTO `persons`( `name`)VALUES ("Венберг М.");
INSERT INTO `persons`( `name`)VALUES ("Венустов В.");
INSERT INTO `persons`( `name`)VALUES ("Вержбицкий");
INSERT INTO `persons`( `name`)VALUES ("Вилларский");
INSERT INTO `persons`( `name`)VALUES ("Вильчевский Э.");
INSERT INTO `persons`( `name`)VALUES ("Владимир Александрович (великий князь)");
INSERT INTO `persons`( `name`)VALUES ("Власов С.");
INSERT INTO `persons`( `name`)VALUES ("Воздвиженский В.");
INSERT INTO `persons`( `name`)VALUES ("Волейко В. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Волков");
INSERT INTO `persons`( `name`)VALUES ("Володзко Г. Ю.");
INSERT INTO `persons`( `name`)VALUES ("Воронов В. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Воронов Ф. В.");
INSERT INTO `persons`( `name`)VALUES ("Воскресенский А.");
INSERT INTO `persons`( `name`)VALUES ("Воскресенский В.");
INSERT INTO `persons`( `name`)VALUES ("Воскресенский П. А.");
INSERT INTO `persons`( `name`)VALUES ("Вяземский С. А.");
INSERT INTO `persons`( `name`)VALUES ("Гаврилов П. И.");
INSERT INTO `persons`( `name`)VALUES ("Гайдебуров П. П.");
INSERT INTO `persons`( `name`)VALUES ("Галченко");
INSERT INTO `persons`( `name`)VALUES ("Гарш А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Гарязин А. Л.");
INSERT INTO `persons`( `name`)VALUES ("Герасим (Ионин)");
INSERT INTO `persons`( `name`)VALUES ("Герцев А. И.");
INSERT INTO `persons`( `name`)VALUES ("Гершанович Д. Г.");
INSERT INTO `persons`( `name`)VALUES ("Гиппиев Н. Г. (Лайне Н.)");
INSERT INTO `persons`( `name`)VALUES ("Глиноецкий Г. П.");
INSERT INTO `persons`( `name`)VALUES ("Глушковский Ю. В.");
INSERT INTO `persons`( `name`)VALUES ("Голубева Г.");
INSERT INTO `persons`( `name`)VALUES ("Гончаревский А. К.");
INSERT INTO `persons`( `name`)VALUES ("Готман М. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Грамицарис А.");
INSERT INTO `persons`( `name`)VALUES ("Граммати Е. Е.");
INSERT INTO `persons`( `name`)VALUES ("Грибанов В. В.");
INSERT INTO `persons`( `name`)VALUES ("Григорьев Г. Г.");
INSERT INTO `persons`( `name`)VALUES ("Григорьева Е. С.");
INSERT INTO `persons`( `name`)VALUES ("Громов И. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Громов П.");
INSERT INTO `persons`( `name`)VALUES ("Гручин М. И.");
INSERT INTO `persons`( `name`)VALUES ("Гюнтер К. К.");
INSERT INTO `persons`( `name`)VALUES ("Данилов Т.");
INSERT INTO `persons`( `name`)VALUES ("Дашков А. В.");
INSERT INTO `persons`( `name`)VALUES ("Дворжицкий К. А.");
INSERT INTO `persons`( `name`)VALUES ("Девяткин В. В.");
INSERT INTO `persons`( `name`)VALUES ("Дейхман Я. П.");
INSERT INTO `persons`( `name`)VALUES ("Де-Ливрон А. А.");
INSERT INTO `persons`( `name`)VALUES ("Дементьев П. В.");
INSERT INTO `persons`( `name`)VALUES ("Денисова А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Дингельштедт Ф.");
INSERT INTO `persons`( `name`)VALUES ("Добре К.");
INSERT INTO `persons`( `name`)VALUES ("Докучаев-Басков К. А.");
INSERT INTO `persons`( `name`)VALUES ("Долгов И.");
INSERT INTO `persons`( `name`)VALUES ("Дорофеев Я.");
INSERT INTO `persons`( `name`)VALUES ("Драницын");
INSERT INTO `persons`( `name`)VALUES ("Друзин М. М.");
INSERT INTO `persons`( `name`)VALUES ("Дуденков В. Д.");
INSERT INTO `persons`( `name`)VALUES ("Дункен");
INSERT INTO `persons`( `name`)VALUES ("Дыклоп Э. П.");
INSERT INTO `persons`( `name`)VALUES ("Дюливье Е. Н.");
INSERT INTO `persons`( `name`)VALUES ("Егоров Г. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Елнинский Н. И.");
INSERT INTO `persons`( `name`)VALUES ("Ерошкин.");
INSERT INTO `persons`( `name`)VALUES ("Ершов С. А.");
INSERT INTO `persons`( `name`)VALUES ("Ефимов А. М.");
INSERT INTO `persons`( `name`)VALUES ("Ефимов С. В.");
INSERT INTO `persons`( `name`)VALUES ("Жеребцов");
INSERT INTO `persons`( `name`)VALUES ("Жигарев П. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Жилинская Е. К.");
INSERT INTO `persons`( `name`)VALUES ("Заводовский М. Н.");
INSERT INTO `persons`( `name`)VALUES ("Загонский Е. К.");
INSERT INTO `persons`( `name`)VALUES ("Зайцев В. М.");
INSERT INTO `persons`( `name`)VALUES ("Зайцев С. В.");
INSERT INTO `persons`( `name`)VALUES ("Закревская Е. М.");
INSERT INTO `persons`( `name`)VALUES ("Заозерский В.");
INSERT INTO `persons`( `name`)VALUES ("Звероловлев Е.");
INSERT INTO `persons`( `name`)VALUES ("Звероловлев Т. А.");
INSERT INTO `persons`( `name`)VALUES ("Золотухин Е. О.");
INSERT INTO `persons`( `name`)VALUES ("Зон А. А.");
INSERT INTO `persons`( `name`)VALUES ("Зубовский М. И.");
INSERT INTO `persons`( `name`)VALUES ("Зубравский К. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Зюльмаев Г.");
INSERT INTO `persons`( `name`)VALUES ("Иванов Г.");
INSERT INTO `persons`( `name`)VALUES ("Иванов М.");
INSERT INTO `persons`( `name`)VALUES ("Иванов Н. П.");
INSERT INTO `persons`( `name`)VALUES ("Ивановский");
INSERT INTO `persons`( `name`)VALUES ("Ивановский Ю.");
INSERT INTO `persons`( `name`)VALUES ("Игнатович Т.");
INSERT INTO `persons`( `name`)VALUES ("Иевлев Д. П.");
INSERT INTO `persons`( `name`)VALUES ("Иннокентий (Левизор)");
INSERT INTO `persons`( `name`)VALUES ("Иоанникий (казначей Соловецкого монастыря)");
INSERT INTO `persons`( `name`)VALUES ("Иогансон К. А.");
INSERT INTO `persons`( `name`)VALUES ("Ионафан (Руднев)");
INSERT INTO `persons`( `name`)VALUES ("Исихий (Звероловлев)");
INSERT INTO `persons`( `name`)VALUES ("Июдин И. М.");
INSERT INTO `persons`( `name`)VALUES ("Июдин Ф. Е.");
INSERT INTO `persons`( `name`)VALUES ("Калашников К. А.");
INSERT INTO `persons`( `name`)VALUES ("Каликин В. С.");
INSERT INTO `persons`( `name`)VALUES ("Канорская Г. Н.");
INSERT INTO `persons`( `name`)VALUES ("Капица Л. Л.");
INSERT INTO `persons`( `name`)VALUES ("Карп С. М.");
INSERT INTO `persons`( `name`)VALUES ("Карпин А. Б.");
INSERT INTO `persons`( `name`)VALUES ("Карпов");
INSERT INTO `persons`( `name`)VALUES ("Катун Д. И.");
INSERT INTO `persons`( `name`)VALUES ("Кацеблин П. И.");
INSERT INTO `persons`( `name`)VALUES ("Качалов");
INSERT INTO `persons`( `name`)VALUES ("Качалов П. В.");
INSERT INTO `persons`( `name`)VALUES ("Качикис А.");
INSERT INTO `persons`( `name`)VALUES ("Кермик Ф. Х.");
INSERT INTO `persons`( `name`)VALUES ("Кийскинен А. И.");
INSERT INTO `persons`( `name`)VALUES ("Киселев Г. И.");
INSERT INTO `persons`( `name`)VALUES ("Климов А. И.");
INSERT INTO `persons`( `name`)VALUES ("Клодницкий Г. Э.");
INSERT INTO `persons`( `name`)VALUES ("Клоковский З. И.");
INSERT INTO `persons`( `name`)VALUES ("Ключарева А. А.");
INSERT INTO `persons`( `name`)VALUES ("Кобелев П.");
INSERT INTO `persons`( `name`)VALUES ("Ковалевский Л. В.");
INSERT INTO `persons`( `name`)VALUES ("Козлов Т.");
INSERT INTO `persons`( `name`)VALUES ("Козырев И. И.");
INSERT INTO `persons`( `name`)VALUES ("Колмовский Л. Н.");
INSERT INTO `persons`( `name`)VALUES ("Колосенок С. В.");
INSERT INTO `persons`( `name`)VALUES ("Компанеец Д.");
INSERT INTO `persons`( `name`)VALUES ("Коненков С. Т.");
INSERT INTO `persons`( `name`)VALUES ("Коновницын П. П.");
INSERT INTO `persons`( `name`)VALUES ("Кононов Ф.");
INSERT INTO `persons`( `name`)VALUES ("Кораблев А. С.");
INSERT INTO `persons`( `name`)VALUES ("Корндорф А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Костюк");
INSERT INTO `persons`( `name`)VALUES ("Косцепецкий");
INSERT INTO `persons`( `name`)VALUES ("Краверский А. В.");
INSERT INTO `persons`( `name`)VALUES ("Кравченко А. И.");
INSERT INTO `persons`( `name`)VALUES ("Кратц К. О.");
INSERT INTO `persons`( `name`)VALUES ("Кретковский К. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Кридин П. В.");
INSERT INTO `persons`( `name`)VALUES ("Кротова Н. А.");
INSERT INTO `persons`( `name`)VALUES ("Крохина");
INSERT INTO `persons`( `name`)VALUES ("Крутяков П. И.");
INSERT INTO `persons`( `name`)VALUES ("Крылов А. Я.");
INSERT INTO `persons`( `name`)VALUES ("Крылов Н. М.");
INSERT INTO `persons`( `name`)VALUES ("Кубагин И");
INSERT INTO `persons`( `name`)VALUES ("Кудряшов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Кузьмин");
INSERT INTO `persons`( `name`)VALUES ("Кузьмин А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Куликовский Г. И.");
INSERT INTO `persons`( `name`)VALUES ("Куткевич А. И.");
INSERT INTO `persons`( `name`)VALUES ("Кутузов А. А.");
INSERT INTO `persons`( `name`)VALUES ("Кутузов М. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Лаварелло М.");
INSERT INTO `persons`( `name`)VALUES ("Лавров");
INSERT INTO `persons`( `name`)VALUES ("Ланговой С. В.");
INSERT INTO `persons`( `name`)VALUES ("Лачинов");
INSERT INTO `persons`( `name`)VALUES ("Левенштейн М. С.");
INSERT INTO `persons`( `name`)VALUES ("Леви");
INSERT INTO `persons`( `name`)VALUES ("Леви М. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Левин Л. Г.");
INSERT INTO `persons`( `name`)VALUES ("Лежиев");
INSERT INTO `persons`( `name`)VALUES ("Лемсен М.");
INSERT INTO `persons`( `name`)VALUES ("Ленин Н. В.");
INSERT INTO `persons`( `name`)VALUES ("Ли Ки Ву");
INSERT INTO `persons`( `name`)VALUES ("Линдгрен А.");
INSERT INTO `persons`( `name`)VALUES ("Липкин");
INSERT INTO `persons`( `name`)VALUES ("Логинов");
INSERT INTO `persons`( `name`)VALUES ("Лузгин В. Н.");
INSERT INTO `persons`( `name`)VALUES ("Лукас Д.");
INSERT INTO `persons`( `name`)VALUES ("Лукин И. С.");
INSERT INTO `persons`( `name`)VALUES ("Лукс К. И.");
INSERT INTO `persons`( `name`)VALUES ("Львов");
INSERT INTO `persons`( `name`)VALUES ("Любовина М. Н.");
INSERT INTO `persons`( `name`)VALUES ("Лядинский Н. П.");
INSERT INTO `persons`( `name`)VALUES ("Мазуровский Л. А.");
INSERT INTO `persons`( `name`)VALUES ("Майстерман С. А.");
INSERT INTO `persons`( `name`)VALUES ("Макаров Г.");
INSERT INTO `persons`( `name`)VALUES ("Маковская Н. А.");
INSERT INTO `persons`( `name`)VALUES ("Максимов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Максимова М.");
INSERT INTO `persons`( `name`)VALUES ("Максютенко Б. М.");
INSERT INTO `persons`( `name`)VALUES ("Малокрошечный И. И.");
INSERT INTO `persons`( `name`)VALUES ("Маминов И. А.");
INSERT INTO `persons`( `name`)VALUES ("Мареш И. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Марин Н. М.");
INSERT INTO `persons`( `name`)VALUES ("Маркконен Э. В.");
INSERT INTO `persons`( `name`)VALUES ("Марков Г. Н.");
INSERT INTO `persons`( `name`)VALUES ("Мартьянов А.");
INSERT INTO `persons`( `name`)VALUES ("Маттилайнен");
INSERT INTO `persons`( `name`)VALUES ("Мауну");
INSERT INTO `persons`( `name`)VALUES ("Машаров Ф. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Мелик-Шахназаров");
INSERT INTO `persons`( `name`)VALUES ("Мелленберг Э. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Мемнонов В. В.");
INSERT INTO `persons`( `name`)VALUES ("Мензенкампф фон Ю.");
INSERT INTO `persons`( `name`)VALUES ("Меркульев А.");
INSERT INTO `persons`( `name`)VALUES ("Мертенс В. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Мешель");
INSERT INTO `persons`( `name`)VALUES ("Мигаловский К. А.");
INSERT INTO `persons`( `name`)VALUES ("Мижуев К.");
INSERT INTO `persons`( `name`)VALUES ("Мизеров М. А.");
INSERT INTO `persons`( `name`)VALUES ("Миницкий С. И.");
INSERT INTO `persons`( `name`)VALUES ("Миронков А.");
INSERT INTO `persons`( `name`)VALUES ("Мнацаканов Г. С.");
INSERT INTO `persons`( `name`)VALUES ("Морозов М.");
INSERT INTO `persons`( `name`)VALUES ("Нарин В. Н.");
INSERT INTO `persons`( `name`)VALUES ("Нафанаил (архимандрит)");
INSERT INTO `persons`( `name`)VALUES ("Небольсин");
INSERT INTO `persons`( `name`)VALUES ("Немирович-Данченко Г. А.");
INSERT INTO `persons`( `name`)VALUES ("нет");
INSERT INTO `persons`( `name`)VALUES ("Никифоров Е.");
INSERT INTO `persons`( `name`)VALUES ("Никольский В.");
INSERT INTO `persons`( `name`)VALUES ("Нобель Л.");
INSERT INTO `persons`( `name`)VALUES ("Носов М. Н.");
INSERT INTO `persons`( `name`)VALUES ("Нюгрен К.");
INSERT INTO `persons`( `name`)VALUES ("Нярвяйнен И. С.");
INSERT INTO `persons`( `name`)VALUES ("Озеров");
INSERT INTO `persons`( `name`)VALUES ("Окуньков С. Г.");
INSERT INTO `persons`( `name`)VALUES ("Ольга Константиновна (королева)");
INSERT INTO `persons`( `name`)VALUES ("Ольхин");
INSERT INTO `persons`( `name`)VALUES ("Островский А. Г.");
INSERT INTO `persons`( `name`)VALUES ("Охотин В.");
INSERT INTO `persons`( `name`)VALUES ("Охотин К. П.");
INSERT INTO `persons`( `name`)VALUES ("Ошевенский");
INSERT INTO `persons`( `name`)VALUES ("Павел (Доброхотов)");
INSERT INTO `persons`( `name`)VALUES ("Павлов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Павлов П. П.");
INSERT INTO `persons`( `name`)VALUES ("Павловский А.");
INSERT INTO `persons`( `name`)VALUES ("Падорин А. (Крузе Б.)");
INSERT INTO `persons`( `name`)VALUES ("Палибин А.");
INSERT INTO `persons`( `name`)VALUES ("Пантелеев С. П.");
INSERT INTO `persons`( `name`)VALUES ("Парамошков Г. Г.");
INSERT INTO `persons`( `name`)VALUES ("Парфенов В. М.");
INSERT INTO `persons`( `name`)VALUES ("Педдер А. Ю.");
INSERT INTO `persons`( `name`)VALUES ("Пекарская");
INSERT INTO `persons`( `name`)VALUES ("Пекшуев");
INSERT INTO `persons`( `name`)VALUES ("Перфильев К. Н.");
INSERT INTO `persons`( `name`)VALUES ("Петров");
INSERT INTO `persons`( `name`)VALUES ("Петров Н. В.");
INSERT INTO `persons`( `name`)VALUES ("Петтай В. Л.");
INSERT INTO `persons`( `name`)VALUES ("Петухов");
INSERT INTO `persons`( `name`)VALUES ("Пешаков И.");
INSERT INTO `persons`( `name`)VALUES ("Пикин М. П.");
INSERT INTO `persons`( `name`)VALUES ("Пикин Н. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Пилко Н. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Пименов Г. Е.");
INSERT INTO `persons`( `name`)VALUES ("Пименов Е. Г.");
INSERT INTO `persons`( `name`)VALUES ("Пименова А. Н.");
INSERT INTO `persons`( `name`)VALUES ("Пипирас А. Д.");
INSERT INTO `persons`( `name`)VALUES ("Пира Ла Д.");
INSERT INTO `persons`( `name`)VALUES ("Плесская А. Я.");
INSERT INTO `persons`( `name`)VALUES ("Подкопаев");
INSERT INTO `persons`( `name`)VALUES ("Попов А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Попов Н. М.");
INSERT INTO `persons`( `name`)VALUES ("Постоянов В. В.");
INSERT INTO `persons`( `name`)VALUES ("Правдин И. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Правдин М. Н.");
INSERT INTO `persons`( `name`)VALUES ("Преженцов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Прокконен П. С.");
INSERT INTO `persons`( `name`)VALUES ("Протасьев Н. В.");
INSERT INTO `persons`( `name`)VALUES ("Прохоров В. Д.");
INSERT INTO `persons`( `name`)VALUES ("Прохоров И. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Прохоров Ф. И.");
INSERT INTO `persons`( `name`)VALUES ("Прушевский В. Р.");
INSERT INTO `persons`( `name`)VALUES ("Путин В. В.");
INSERT INTO `persons`( `name`)VALUES ("Путята В. А.");
INSERT INTO `persons`( `name`)VALUES ("Пущин И. П.");
INSERT INTO `persons`( `name`)VALUES ("Рассветов Л.");
INSERT INTO `persons`( `name`)VALUES ("Ратник К. К.");
INSERT INTO `persons`( `name`)VALUES ("Ребовский М. Е.");
INSERT INTO `persons`( `name`)VALUES ("Рейнонен Э. Э.");
INSERT INTO `persons`( `name`)VALUES ("Рейхардт");
INSERT INTO `persons`( `name`)VALUES ("Рейхенбах");
INSERT INTO `persons`( `name`)VALUES ("Рекс Т.");
INSERT INTO `persons`( `name`)VALUES ("Рогов Г.");
INSERT INTO `persons`( `name`)VALUES ("Рогозин В. А.");
INSERT INTO `persons`( `name`)VALUES ("Рожнов");
INSERT INTO `persons`( `name`)VALUES ("Розенштандт Г.");
INSERT INTO `persons`( `name`)VALUES ("Романов Н.");
INSERT INTO `persons`( `name`)VALUES ("Романов С.");
INSERT INTO `persons`( `name`)VALUES ("Рудницкий А. М.");
INSERT INTO `persons`( `name`)VALUES ("Русаков П. А.");
INSERT INTO `persons`( `name`)VALUES ("Русаков А. А.");
INSERT INTO `persons`( `name`)VALUES ("Рыбин Ф. С.");
INSERT INTO `persons`( `name`)VALUES ("Рябоевы");
INSERT INTO `persons`( `name`)VALUES ("Саареля К. А.");
INSERT INTO `persons`( `name`)VALUES ("Саблин");
INSERT INTO `persons`( `name`)VALUES ("Савинов");
INSERT INTO `persons`( `name`)VALUES ("Сарычев А. Т.");
INSERT INTO `persons`( `name`)VALUES ("Селиверстов М.");
INSERT INTO `persons`( `name`)VALUES ("Семенов А.");
INSERT INTO `persons`( `name`)VALUES ("Семенов А. С.");
INSERT INTO `persons`( `name`)VALUES ("Сергеев И. И. (Иоанн Кронштадтский)");
INSERT INTO `persons`( `name`)VALUES ("Сетеля Э. Н.");
INSERT INTO `persons`( `name`)VALUES ("Сигов В. П.");
INSERT INTO `persons`( `name`)VALUES ("Сидоренко В. В.");
INSERT INTO `persons`( `name`)VALUES ("Симанов С.");
INSERT INTO `persons`( `name`)VALUES ("Синисало Г.-Р. Н.");
INSERT INTO `persons`( `name`)VALUES ("Синцов М. А.");
INSERT INTO `persons`( `name`)VALUES ("Славинский К. П.");
INSERT INTO `persons`( `name`)VALUES ("Слепцов А. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Смирнов И. В.");
INSERT INTO `persons`( `name`)VALUES ("Смоликова А. А.");
INSERT INTO `persons`( `name`)VALUES ("Смоликова Е. К.");
INSERT INTO `persons`( `name`)VALUES ("Смотрич");
INSERT INTO `persons`( `name`)VALUES ("Собчак М. Я.");
INSERT INTO `persons`( `name`)VALUES ("Соколова Е. Т.");
INSERT INTO `persons`( `name`)VALUES ("Сольберг Ф. Г.");
INSERT INTO `persons`( `name`)VALUES ("Сотикова А. Н.");
INSERT INTO `persons`( `name`)VALUES ("Спадаренков П.");
INSERT INTO `persons`( `name`)VALUES ("Сретенский Е. С.");
INSERT INTO `persons`( `name`)VALUES ("Ставропуло Н.");
INSERT INTO `persons`( `name`)VALUES ("Стенберг Э.");
INSERT INTO `persons`( `name`)VALUES ("Стручков Н. С.");
INSERT INTO `persons`( `name`)VALUES ("Студитов П. В.");
INSERT INTO `persons`( `name`)VALUES ("Сулимейко");
INSERT INTO `persons`( `name`)VALUES ("Суханов");
INSERT INTO `persons`( `name`)VALUES ("Сухонкин В.");
INSERT INTO `persons`( `name`)VALUES ("Табарданова Г. А.");
INSERT INTO `persons`( `name`)VALUES ("Танасейчук Г. Я.");
INSERT INTO `persons`( `name`)VALUES ("Таратайкин Г. В.");
INSERT INTO `persons`( `name`)VALUES ("Тарле Ц. Д.");
INSERT INTO `persons`( `name`)VALUES ("Теребухин");
INSERT INTO `persons`( `name`)VALUES ("Тетерников Ф. К.");
INSERT INTO `persons`( `name`)VALUES ("Тимофеев");
INSERT INTO `persons`( `name`)VALUES ("Тимошин Н. М.");
INSERT INTO `persons`( `name`)VALUES ("Титов Алексей Иванович");
INSERT INTO `persons`( `name`)VALUES ("Титов П.");
INSERT INTO `persons`( `name`)VALUES ("Тихонов И. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Торшилова М.");
INSERT INTO `persons`( `name`)VALUES ("Троцкая К.");
INSERT INTO `persons`( `name`)VALUES ("Тулин Д. И.");
INSERT INTO `persons`( `name`)VALUES ("Тутолмин Т. И.");
INSERT INTO `persons`( `name`)VALUES ("Ураев Р. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Успенский В. Л.");
INSERT INTO `persons`( `name`)VALUES ("Федоров");
INSERT INTO `persons`( `name`)VALUES ("Федоров Ф.");
INSERT INTO `persons`( `name`)VALUES ("Фепонов Н. М.");
INSERT INTO `persons`( `name`)VALUES ("Флигельман");
INSERT INTO `persons`( `name`)VALUES ("Флодерус Б.");
INSERT INTO `persons`( `name`)VALUES ("Фогель Ф. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Форкейн");
INSERT INTO `persons`( `name`)VALUES ("Франц Р. Я.");
INSERT INTO `persons`( `name`)VALUES ("Фрибес В. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Фридриксен Л.");
INSERT INTO `persons`( `name`)VALUES ("Фридрихсон А. И.");
INSERT INTO `persons`( `name`)VALUES ("Фролов Б. Г.");
INSERT INTO `persons`( `name`)VALUES ("Фурсов В.");
INSERT INTO `persons`( `name`)VALUES ("Харламов Б. В.");
INSERT INTO `persons`( `name`)VALUES ("Харькин Г. С.");
INSERT INTO `persons`( `name`)VALUES ("Хлебников С. А.");
INSERT INTO `persons`( `name`)VALUES ("Ходотов");
INSERT INTO `persons`( `name`)VALUES ("Холодный М. П.");
INSERT INTO `persons`( `name`)VALUES ("Холодный П. Я.");
INSERT INTO `persons`( `name`)VALUES ("Хорошнев Н.");
INSERT INTO `persons`( `name`)VALUES ("Хультен Э.");
INSERT INTO `persons`( `name`)VALUES ("Хумек Г. И.");
INSERT INTO `persons`( `name`)VALUES ("Цвиллинг И. И.");
INSERT INTO `persons`( `name`)VALUES ("Цибулькин Н. Н.");
INSERT INTO `persons`( `name`)VALUES ("Цинзерлинг Ю. Д.");
INSERT INTO `persons`( `name`)VALUES ("Цолан И. И.");
INSERT INTO `persons`( `name`)VALUES ("Цолнер Ф. Ф.");
INSERT INTO `persons`( `name`)VALUES ("Цумалья де П.");
INSERT INTO `persons`( `name`)VALUES ("Чеботарев В. П.");
INSERT INTO `persons`( `name`)VALUES ("Чепаков П.");
INSERT INTO `persons`( `name`)VALUES ("Чертов К. А.");
INSERT INTO `persons`( `name`)VALUES ("Чильман А. О.");
INSERT INTO `persons`( `name`)VALUES ("Чудинов Л. П.");
INSERT INTO `persons`( `name`)VALUES ("Чудинов П.");
INSERT INTO `persons`( `name`)VALUES ("Чужинов И. П.");
INSERT INTO `persons`( `name`)VALUES ("Шалопанов А. П.");
INSERT INTO `persons`( `name`)VALUES ("Шамец И. К.");
INSERT INTO `persons`( `name`)VALUES ("Шанин");
INSERT INTO `persons`( `name`)VALUES ("Шаноний Д.");
INSERT INTO `persons`( `name`)VALUES ("Шапошников П.");
INSERT INTO `persons`( `name`)VALUES ("Швидко Л. А.");
INSERT INTO `persons`( `name`)VALUES ("Шегельман И. Р.");
INSERT INTO `persons`( `name`)VALUES ("Шежемский С. В.");
INSERT INTO `persons`( `name`)VALUES ("Шелюков Ф. С.");
INSERT INTO `persons`( `name`)VALUES ("Шершед А.");
INSERT INTO `persons`( `name`)VALUES ("Шехирин С. И.");
INSERT INTO `persons`( `name`)VALUES ("Шехирина Н. И.");
INSERT INTO `persons`( `name`)VALUES ("Шипилин");
INSERT INTO `persons`( `name`)VALUES ("Ширипин М. Е.");
INSERT INTO `persons`( `name`)VALUES ("Шихалев Ф. М.");
INSERT INTO `persons`( `name`)VALUES ("Шишов А. Н.");
INSERT INTO `persons`( `name`)VALUES ("Шишов Е. Н.");
INSERT INTO `persons`( `name`)VALUES ("Шкурбало В. М.");
INSERT INTO `persons`( `name`)VALUES ("Шмейс");
INSERT INTO `persons`( `name`)VALUES ("Шмидт Я. К.");
INSERT INTO `persons`( `name`)VALUES ("Штейнзат Е. С.");
INSERT INTO `persons`( `name`)VALUES ("Шубников");
INSERT INTO `persons`( `name`)VALUES ("Щелкунов");
INSERT INTO `persons`( `name`)VALUES ("Эльснер");
INSERT INTO `persons`( `name`)VALUES ("Эркко Ю. Ю.");
INSERT INTO `persons`( `name`)VALUES ("Ягор Ж. К.");
INSERT INTO `persons`( `name`)VALUES ("Ярышев");
INSERT INTO `persons`( `name`)VALUES ("Яскунов С. М.");
INSERT INTO `persons`( `name`)VALUES ("Ястребов А.");
INSERT INTO `persons`( `name`)VALUES ("Ятцеров П. Г.");
