INSERT INTO `persons_test` VALUES ("1", "Абросимов П. П.", "Абросимов П. П.");
INSERT INTO `persons_test` VALUES ("2", "Авзотис Г.", "Авзотис Г.");
INSERT INTO `persons_test` VALUES ("3", "Аглицкий Г. А.", "Аглицкий Г. А.");
INSERT INTO `persons_test` VALUES ("4", "Агню Д.", "Агню Д.");
INSERT INTO `persons_test` VALUES ("5", "Адамович С. М.", "Адамович С. М.");
INSERT INTO `persons_test` VALUES ("6", "Александров", "Александров");
INSERT INTO `persons_test` VALUES ("7", "Алешин", "Алешин");
INSERT INTO `persons_test` VALUES ("8", "Алешина А. Б.", "Алешина А. Б.");
INSERT INTO `persons_test` VALUES ("9", "Альперович Б. С.", "Альперович Б. С.");
INSERT INTO `persons_test` VALUES ("10", "Альшванг А. А.", "Альшванг А. А.");
INSERT INTO `persons_test` VALUES ("11", "Андреев Н.", "Андреев Н.");
INSERT INTO `persons_test` VALUES ("12", "Андреев С.", "Андреев С.");
INSERT INTO `persons_test` VALUES ("13", "Андреева Н.", "Андреева Н.");
INSERT INTO `persons_test` VALUES ("14", "Андрианов Н. Н.", "Андрианов Н. Н.");
INSERT INTO `persons_test` VALUES ("15", "Антоновский", "Антоновский");
INSERT INTO `persons_test` VALUES ("16", "Аргатов И. И.", "Аргатов И. И.");
INSERT INTO `persons_test` VALUES ("17", "Аркадий (Федоров)", "Аркадий (Федоров)");
INSERT INTO `persons_test` VALUES ("18", "Арсеньев Ю. К.", "Арсеньев Ю. К.");
INSERT INTO `persons_test` VALUES ("19", "Архипова П. Е.", "Архипова П. Е.");
INSERT INTO `persons_test` VALUES ("20", "Афанасьев А. А.", "Афанасьев А. А.");
INSERT INTO `persons_test` VALUES ("21", "Базегский П. И.", "Базегский П. И.");
INSERT INTO `persons_test` VALUES ("22", "Байков Ф.", "Байков Ф.");
INSERT INTO `persons_test` VALUES ("23", "Бакланов Ю. П.", "Бакланов Ю. П.");
INSERT INTO `persons_test` VALUES ("24", "Баландин Т. В.", "Баландин Т. В.");
INSERT INTO `persons_test` VALUES ("25", "Баралл П.", "Баралл П.");
INSERT INTO `persons_test` VALUES ("26", "Баранов Д. О.", "Баранов Д. О.");
INSERT INTO `persons_test` VALUES ("27", "Баранцов А. П.", "Баранцов А. П.");
INSERT INTO `persons_test` VALUES ("28", "Барбашин В. Б.", "Барбашин В. Б.");
INSERT INTO `persons_test` VALUES ("29", "Басинский", "Басинский");
INSERT INTO `persons_test` VALUES ("30", "Башев П. А.", "Башев П. А.");
INSERT INTO `persons_test` VALUES ("31", "Башева А. М.", "Башева А. М.");
INSERT INTO `persons_test` VALUES ("32", "Бек", "Аркадий (Федоров)");
INSERT INTO `persons_test` VALUES ("33", "Белиловский К. А.", "Белиловский К. А.");
INSERT INTO `persons_test` VALUES ("34", "Беляев А. П.", "Беляев А. П.");
INSERT INTO `persons_test` VALUES ("35", "Беляев И. С.", "Беляев И. С.");
INSERT INTO `persons_test` VALUES ("36", "Беляков С. М.", "Беляков С. М.");
INSERT INTO `persons_test` VALUES ("37", "Бенкендорф А. Х.", "Бенкендорф А. Х.");
INSERT INTO `persons_test` VALUES ("38", "Березин", "Березин");
INSERT INTO `persons_test` VALUES ("39", "Бесов", "Бесов");
INSERT INTO `persons_test` VALUES ("40", "Беспальчев А. Ф.", "Беспальчев А. Ф.");
INSERT INTO `persons_test` VALUES ("41", "Благородченков", "Благородченков");
INSERT INTO `persons_test` VALUES ("42", "Блау", "Блау");
INSERT INTO `persons_test` VALUES ("43", "Блок А. А.", "Блок А. А.");
INSERT INTO `persons_test` VALUES ("44", "Бобринский А. А.", "Бобринский А. А.");
INSERT INTO `persons_test` VALUES ("45", "Богданов В.", "Богданов В.");
INSERT INTO `persons_test` VALUES ("46", "Богданов В. Н.", "Богданов В. Н.");
INSERT INTO `persons_test` VALUES ("47", "Богданов М.", "Богданов М.");
INSERT INTO `persons_test` VALUES ("48", "Богданов П.", "Богданов П.");
INSERT INTO `persons_test` VALUES ("49", "Болотников И. М.", "Болотников И. М.");
INSERT INTO `persons_test` VALUES ("50", "Большаков И. П.", "Большаков И. П.");
INSERT INTO `persons_test` VALUES ("51", "Бонбин П.", "Бонбин П.");
INSERT INTO `persons_test` VALUES ("52", "Бржеский В. Ч.", "Бржеский В. Ч.");
INSERT INTO `persons_test` VALUES ("53", "Бронштейн А. Л.", "Бронштейн А. Л.");
INSERT INTO `persons_test` VALUES ("54", "Вавилов Г.А.", "Вавилов Г. А.");
INSERT INTO `persons_test` VALUES ("55", "Вагнер", "Вагнер");
INSERT INTO `persons_test` VALUES ("56", "Валентик И. Я.", "Валентик И. Я.");
INSERT INTO `persons_test` VALUES ("57", "Варзугин Н. П.", "Варзугин Н. П.");
INSERT INTO `persons_test` VALUES ("58", "Вашингтон Д.", "Вашингтон Д.");
INSERT INTO `persons_test` VALUES ("59", "Введенский А. И.", "Введенский А. И.");
INSERT INTO `persons_test` VALUES ("60", "Венберг М.", "Венберг М.");
INSERT INTO `persons_test` VALUES ("61", "Венустов В.", "Венустов В.");
INSERT INTO `persons_test` VALUES ("62", "Вержбицкий", "Вержбицкий");
INSERT INTO `persons_test` VALUES ("63", "Вилларский", "Вилларский");
INSERT INTO `persons_test` VALUES ("64", "Вильчевский Э.", "Вильчевский Э.");
INSERT INTO `persons_test` VALUES ("65", "Владимир Александрович (великий князь)", "Владимир Александрович (великий князь)");
INSERT INTO `persons_test` VALUES ("66", "Власов С.", "Власов С.");
INSERT INTO `persons_test` VALUES ("67", "Воздвиженский В.", "Воздвиженский В.");
INSERT INTO `persons_test` VALUES ("68", "Волейко В. Ф.", "Волейко В. Ф.");
INSERT INTO `persons_test` VALUES ("69", "Волков", "Волков");
INSERT INTO `persons_test` VALUES ("70", "Володзко Г. Ю.", "Володзко Г. Ю.");
INSERT INTO `persons_test` VALUES ("71", "Воронов В. Ф", "Воронов В. Ф.");
INSERT INTO `persons_test` VALUES ("72", "Воронов Ф. В.", "Воронов Ф. В.");
INSERT INTO `persons_test` VALUES ("73", "Воскресенский А", "Воскресенский А.");
INSERT INTO `persons_test` VALUES ("74", "Воскресенский В.", "Воскресенский В.");
INSERT INTO `persons_test` VALUES ("75", "Воскресенский П. А.", "Воскресенский П. А.");
INSERT INTO `persons_test` VALUES ("76", "Вяземский С. А.", "Вяземский С. А.");
INSERT INTO `persons_test` VALUES ("77", "Гаврилов П. И.", "Гаврилов П. И.");
INSERT INTO `persons_test` VALUES ("78", "Гайдебуров П. П.", "Гайдебуров П. П.");
INSERT INTO `persons_test` VALUES ("79", "Галченко", "Галченко");
INSERT INTO `persons_test` VALUES ("80", "Гарш А. Ф.", "Гарш А. Ф.");
INSERT INTO `persons_test` VALUES ("81", "Гарязин А. Л.", "Гарязин А. Л.");
INSERT INTO `persons_test` VALUES ("82", "Герасим (Ионин)", "Герасим (Ионин)");
INSERT INTO `persons_test` VALUES ("83", "Герцев А. И.", "Герцев А. И.");
INSERT INTO `persons_test` VALUES ("84", "Гершанович Д. Г.", "Гершанович Д. Г.");
INSERT INTO `persons_test` VALUES ("85", "Гиппиев Н. Г. (Лайне Н.)", "Гиппиев Н. Г. (Лайне Н.)");
INSERT INTO `persons_test` VALUES ("86", "Глиноецкий Г. П.", "Глиноецкий Г. П.");
INSERT INTO `persons_test` VALUES ("87", "Глушковский Ю. В.", "Глушковский Ю. В.");
INSERT INTO `persons_test` VALUES ("88", "Голубева Г", "Голубева Г.");
INSERT INTO `persons_test` VALUES ("89", "Гончаревский А. К.", "Гончаревский А. К.");
INSERT INTO `persons_test` VALUES ("90", "Готман М. Ф.", "Готман М. Ф.");
INSERT INTO `persons_test` VALUES ("91", "Грамицарис А.", "Грамицарис А.");
INSERT INTO `persons_test` VALUES ("92", "Граммати Е. Е.", "Граммати Е. Е.");
INSERT INTO `persons_test` VALUES ("93", "Грибанов В. В.", "Грибанов В. В.");
INSERT INTO `persons_test` VALUES ("94", "Григорьев Г. Г.", "Григорьев Г. Г.");
INSERT INTO `persons_test` VALUES ("95", "Григорьева Е. С.", "Григорьева Е. С.");
INSERT INTO `persons_test` VALUES ("96", "Громов И. Ф.", "Громов И. Ф.");
INSERT INTO `persons_test` VALUES ("97", "Громов П.", "Громов П.");
INSERT INTO `persons_test` VALUES ("98", "Гручин М. И.", "Гручин М. И.");
INSERT INTO `persons_test` VALUES ("99", "Гюнтер К. К.", "Гюнтер К. К.");
INSERT INTO `persons_test` VALUES ("100", "Данилов Т.", "Данилов Т.");
INSERT INTO `persons_test` VALUES ("101", "Дашков А. В.", "Дашков А. В.");
INSERT INTO `persons_test` VALUES ("102", "Дворжицкий К. А.", "Дворжицкий К. А.");
INSERT INTO `persons_test` VALUES ("103", "Девяткин В. В.", "Девяткин В. В.");
INSERT INTO `persons_test` VALUES ("104", "Дейхман Я. П.", "Дейхман Я. П.");
INSERT INTO `persons_test` VALUES ("105", "Де-Ливрон А. А.", "Де-Ливрон А. А.");
INSERT INTO `persons_test` VALUES ("106", "дементьев П. В.", "Дементьев П. В.");
INSERT INTO `persons_test` VALUES ("107", "Денисова А. Ф.", "Денисова А. Ф.");
INSERT INTO `persons_test` VALUES ("108", "Дингельштедт Ф.", "Дингельштедт Ф.");
INSERT INTO `persons_test` VALUES ("109", "Добре К.", "Добре К.");
INSERT INTO `persons_test` VALUES ("110", "Докучаев-Басков К. А.", "Докучаев-Басков К. А.");
INSERT INTO `persons_test` VALUES ("111", "Долгов И.", "Долгов И.");
INSERT INTO `persons_test` VALUES ("112", "Дорофеев Я.", "Дорофеев Я.");
INSERT INTO `persons_test` VALUES ("113", "Драницын", "Драницын");
INSERT INTO `persons_test` VALUES ("114", "Друзин М. М.", "Друзин М. М.");
INSERT INTO `persons_test` VALUES ("115", "Дуденков В. Д.", "Дуденков В. Д.");
INSERT INTO `persons_test` VALUES ("116", "Дункен", "Дункен");
INSERT INTO `persons_test` VALUES ("117", "Дыклоп Э. П.", "Дыклоп Э. П.");
INSERT INTO `persons_test` VALUES ("118", "Дюливье Е. Н.", "Дюливье Е. Н.");
INSERT INTO `persons_test` VALUES ("119", "Егоров Г. Ф.", "Егоров Г. Ф.");
INSERT INTO `persons_test` VALUES ("120", "Елнинский Н. И.", "Елнинский Н. И.");
INSERT INTO `persons_test` VALUES ("121", "Ерошкин.", "Ерошкин.");
INSERT INTO `persons_test` VALUES ("122", "Ершов С. А.", "Ершов С. А.");
INSERT INTO `persons_test` VALUES ("123", "Ефимов А. М.", "Ефимов А. М.");
INSERT INTO `persons_test` VALUES ("124", "Ефимов С. В.", "Ефимов С. В.");
INSERT INTO `persons_test` VALUES ("125", "Жеребцов", "Жеребцов");
INSERT INTO `persons_test` VALUES ("126", "Жигарев П. Ф.", "Жигарев П. Ф.");
INSERT INTO `persons_test` VALUES ("127", "Жилинская Е. К.", "Жилинская Е. К.");
INSERT INTO `persons_test` VALUES ("128", "Заводовский М. Н.", "Заводовский М. Н.");
INSERT INTO `persons_test` VALUES ("129", "Загонский Е. К.", "Загонский Е. К.");
INSERT INTO `persons_test` VALUES ("130", "Зайцев В. М.", "Зайцев В. М.");
INSERT INTO `persons_test` VALUES ("131", "Зайцев С. В.", "Зайцев С. В.");
INSERT INTO `persons_test` VALUES ("132", "Закревская Е. М.", "Закревская Е. М.");
INSERT INTO `persons_test` VALUES ("133", "Заозерский В.", "Заозерский В.");
INSERT INTO `persons_test` VALUES ("134", "Звероловлев Е.", "Звероловлев Е.");
INSERT INTO `persons_test` VALUES ("135", "Звероловлев Т. А.", "Звероловлев Т. А.");
INSERT INTO `persons_test` VALUES ("136", "Золотухин Е. О.", "Золотухин Е. О.");
INSERT INTO `persons_test` VALUES ("137", "Зон А. А.", "Зон А. А.");
INSERT INTO `persons_test` VALUES ("138", "Зубовский М. И.", "Зубовский М. И.");
INSERT INTO `persons_test` VALUES ("139", "Зубравский К. Ф.", "Зубравский К. Ф.");
INSERT INTO `persons_test` VALUES ("140", "Зюльмаев Г.", "Зюльмаев Г.");
INSERT INTO `persons_test` VALUES ("141", "Иванов Г.", "Иванов Г.");
INSERT INTO `persons_test` VALUES ("142", "Иванов М.", "Иванов М.");
INSERT INTO `persons_test` VALUES ("143", "Иванов Н. П.", "Иванов Н. П.");
INSERT INTO `persons_test` VALUES ("144", "Ивановский", "Ивановский");
INSERT INTO `persons_test` VALUES ("145", "Ивановский Ю.", "Ивановский Ю.");
INSERT INTO `persons_test` VALUES ("146", "Игнатович Т.", "Игнатович Т.");
INSERT INTO `persons_test` VALUES ("147", "Иевлев Д. П.", "Иевлев Д. П.");
INSERT INTO `persons_test` VALUES ("148", "Иннокентий (Левизор)", "Иннокентий (Левизор)");
INSERT INTO `persons_test` VALUES ("149", "Иоанникий (казначей Соловецкого монастыря)", "Иоанникий (казначей Соловецкого монастыря)");
INSERT INTO `persons_test` VALUES ("150", "Иоганскон К.", "Иогансон К. А.");
INSERT INTO `persons_test` VALUES ("151", "Ионафан (Руднев)", "Ионафан (Руднев)");
INSERT INTO `persons_test` VALUES ("152", "Исихий (Звероловлев)", "Исихий (Звероловлев)");
INSERT INTO `persons_test` VALUES ("153", "Июдин И. М.", "Июдин И. М.");
INSERT INTO `persons_test` VALUES ("154", "Июдин Ф. Е.", "Июдин Ф. Е.");
INSERT INTO `persons_test` VALUES ("155", "Калашников К. А.", "Калашников К. А.");
INSERT INTO `persons_test` VALUES ("156", "Каликин В. С.", "Каликин В. С.");
INSERT INTO `persons_test` VALUES ("157", "Калинин А.", "Ионафан (Руднев)");
INSERT INTO `persons_test` VALUES ("158", "Канорская Г. Н.", "Канорская Г. Н.");
INSERT INTO `persons_test` VALUES ("159", "Капица Л. Л.", "Капица Л. Л.");
INSERT INTO `persons_test` VALUES ("160", "Карп С. М.", "Карп С. М.");
INSERT INTO `persons_test` VALUES ("161", "Карпин А. Б.", "Карпин А. Б.");
INSERT INTO `persons_test` VALUES ("162", "Карпов", "Карпов");
INSERT INTO `persons_test` VALUES ("163", "Катун Д. И.", "Катун Д. И.");
INSERT INTO `persons_test` VALUES ("164", "Кацеблин П. И.", "Кацеблин П. И.");
INSERT INTO `persons_test` VALUES ("165", "Качалов", "Качалов");
INSERT INTO `persons_test` VALUES ("166", "Качалов П. В.", "Качалов П. В.");
INSERT INTO `persons_test` VALUES ("167", "Качикис А.", "Качикис А.");
INSERT INTO `persons_test` VALUES ("168", "Кермик Ф. Х.", "Кермик Ф. Х.");
INSERT INTO `persons_test` VALUES ("169", "Кийскинен А. И.", "Кийскинен А. И.");
INSERT INTO `persons_test` VALUES ("170", "Киселев Г. И.", "Киселев Г. И.");
INSERT INTO `persons_test` VALUES ("171", "Климов А. И.", "Климов А. И.");
INSERT INTO `persons_test` VALUES ("172", "Клодницкий Г. Э.", "Клодницкий Г. Э.");
INSERT INTO `persons_test` VALUES ("173", "Клоковский З. И.", "Клоковский З. И.");
INSERT INTO `persons_test` VALUES ("174", "Ключарева А. А.", "Ключарева А. А.");
INSERT INTO `persons_test` VALUES ("175", "Кобелев П.", "Кобелев П.");
INSERT INTO `persons_test` VALUES ("176", "Ковалевский Л. В.", "Ковалевский Л. В.");
INSERT INTO `persons_test` VALUES ("177", "Козлов Т.", "Козлов Т.");
INSERT INTO `persons_test` VALUES ("178", "Козырев И. И.", "Козырев И. И.");
INSERT INTO `persons_test` VALUES ("179", "Колмовский Л. Н.", "Колмовский Л. Н.");
INSERT INTO `persons_test` VALUES ("180", "Колосенок С. В.", "Колосенок С. В.");
INSERT INTO `persons_test` VALUES ("181", "Компанеец Д", "Компанеец Д.");
INSERT INTO `persons_test` VALUES ("182", "Коненков С. Т.", "Коненков С. Т.");
INSERT INTO `persons_test` VALUES ("183", "Коновницын П. П.", "Коновницын П. П.");
INSERT INTO `persons_test` VALUES ("184", "Кононов Ф.", "Кононов Ф.");
INSERT INTO `persons_test` VALUES ("185", "Кораблев А. С.", "Кораблев А. С.");
INSERT INTO `persons_test` VALUES ("186", "Корндорф А. Ф.", "Корндорф А. Ф.");
INSERT INTO `persons_test` VALUES ("187", "Костюк", "Костюк");
INSERT INTO `persons_test` VALUES ("188", "Косцепецкий", "Косцепецкий");
INSERT INTO `persons_test` VALUES ("189", "Краверский А. В.", "Краверский А. В.");
INSERT INTO `persons_test` VALUES ("190", "Кравченко А. И.", "Кравченко А. И.");
INSERT INTO `persons_test` VALUES ("191", "Кратц К. О.", "Кратц К. О.");
INSERT INTO `persons_test` VALUES ("192", "Кретковский К. Ф.", "Кретковский К. Ф.");
INSERT INTO `persons_test` VALUES ("193", "Кридин П. В.", "Кридин П. В.");
INSERT INTO `persons_test` VALUES ("194", "Кротова Н. А.", "Кротова Н. А.");
INSERT INTO `persons_test` VALUES ("195", "Крохина", "Крохина");
INSERT INTO `persons_test` VALUES ("196", "Крутяков П. И.", "Крутяков П. И.");
INSERT INTO `persons_test` VALUES ("197", "Крылов А. Я.", "Крылов А. Я.");
INSERT INTO `persons_test` VALUES ("198", "Крылов Н. М.", "Крылов Н. М.");
INSERT INTO `persons_test` VALUES ("199", "Кубагин И", "Кубагин И");
INSERT INTO `persons_test` VALUES ("200", "Кудряшов А. П.", "Кудряшов А. П.");
INSERT INTO `persons_test` VALUES ("201", "Кузьмин", "Кузьмин");
INSERT INTO `persons_test` VALUES ("202", "Кузьмин А. Ф.", "Кузьмин А. Ф.");
INSERT INTO `persons_test` VALUES ("203", "Куликовский Г. И.", "Куликовский Г. И.");
INSERT INTO `persons_test` VALUES ("204", "Куткевич А. И.", "Куткевич А. И.");
INSERT INTO `persons_test` VALUES ("205", "Кутузов А. А.", "Кутузов А. А.");
INSERT INTO `persons_test` VALUES ("206", "Кутузов М. Ф.", "Кутузов М. Ф.");
INSERT INTO `persons_test` VALUES ("207", "Лаварелло М.", "Лаварелло М.");
INSERT INTO `persons_test` VALUES ("208", "Лавров", "Лавров");
INSERT INTO `persons_test` VALUES ("209", "Ланговой С. В.", "Ланговой С. В.");
INSERT INTO `persons_test` VALUES ("210", "Лачинов", "Лачинов");
INSERT INTO `persons_test` VALUES ("211", "Левенштейн М. С.", "Левенштейн М. С.");
INSERT INTO `persons_test` VALUES ("212", "Леви", "Леви");
INSERT INTO `persons_test` VALUES ("213", "Леви М. Ф.", "Леви М. Ф.");
INSERT INTO `persons_test` VALUES ("214", "Левин Л. Г.", "Левин Л. Г.");
INSERT INTO `persons_test` VALUES ("215", "Лежиев", "Лежиев");
INSERT INTO `persons_test` VALUES ("216", "Лемсен М.", "Лемсен М.");
INSERT INTO `persons_test` VALUES ("217", "Ленин Н. В.", "Ленин Н. В.");
INSERT INTO `persons_test` VALUES ("218", "Ли Ки Ву", "Ли Ки Ву");
INSERT INTO `persons_test` VALUES ("219", "Линдгрен А.", "Линдгрен А.");
INSERT INTO `persons_test` VALUES ("220", "Липкин", "Липкин");
INSERT INTO `persons_test` VALUES ("221", "Логинов", "Логинов");
INSERT INTO `persons_test` VALUES ("222", "Лузгин В. Н.", "Лузгин В. Н.");
INSERT INTO `persons_test` VALUES ("223", "Лукас Д.", "Лукас Д.");
INSERT INTO `persons_test` VALUES ("224", "Лукин И. С.", "Лукин И. С.");
INSERT INTO `persons_test` VALUES ("225", "Лукс К. И.", "Лукс К. И.");
INSERT INTO `persons_test` VALUES ("226", "Львов", "Львов");
INSERT INTO `persons_test` VALUES ("227", "Любовина М. Н.", "Любовина М. Н.");
INSERT INTO `persons_test` VALUES ("228", "Лядинский Н. П.", "Лядинский Н. П.");
INSERT INTO `persons_test` VALUES ("229", "Мазуровский Л. А.", "Мазуровский Л. А.");
INSERT INTO `persons_test` VALUES ("230", "Майстерман С. А.", "Майстерман С. А.");
INSERT INTO `persons_test` VALUES ("231", "Макаров Г.", "Макаров Г.");
INSERT INTO `persons_test` VALUES ("232", "Маковская Н. А.", "Маковская Н. А.");
INSERT INTO `persons_test` VALUES ("233", "Максимов А. П.", "Максимов А. П.");
INSERT INTO `persons_test` VALUES ("234", "Максимова М.", "Максимова М.");
INSERT INTO `persons_test` VALUES ("235", "Максютенко Б. М.", "Максютенко Б. М.");
INSERT INTO `persons_test` VALUES ("236", "Малокрошечный И. И.", "Малокрошечный И. И.");
INSERT INTO `persons_test` VALUES ("237", "Маминов И. А.", "Маминов И. А.");
INSERT INTO `persons_test` VALUES ("238", "Мареш И. Ф.", "Мареш И. Ф.");
INSERT INTO `persons_test` VALUES ("239", "Марин Н. М.", "Марин Н. М.");
INSERT INTO `persons_test` VALUES ("240", "Маркконен Э. В.", "Маркконен Э. В.");
INSERT INTO `persons_test` VALUES ("241", "Марков Г. Н.", "Марков Г. Н.");
INSERT INTO `persons_test` VALUES ("242", "Мартьянов А.", "Мартьянов А.");
INSERT INTO `persons_test` VALUES ("243", "Маттилайнен", "Маттилайнен");
INSERT INTO `persons_test` VALUES ("244", "Мауну", "Мауну");
INSERT INTO `persons_test` VALUES ("245", "Машаров Ф. Ф.", "Машаров Ф. Ф.");
INSERT INTO `persons_test` VALUES ("246", "Мелик-Шахназаров", "Мелик-Шахназаров");
INSERT INTO `persons_test` VALUES ("247", "Мелленберг Э. Ф.", "Мелленберг Э. Ф.");
INSERT INTO `persons_test` VALUES ("248", "Мемнонов В. В.", "Мемнонов В. В.");
INSERT INTO `persons_test` VALUES ("249", "Мензенкампф фон Ю.", "Мензенкампф фон Ю.");
INSERT INTO `persons_test` VALUES ("250", "Меркульев А.", "Меркульев А.");
INSERT INTO `persons_test` VALUES ("251", "Мертенс В. Ф.", "Мертенс В. Ф.");
INSERT INTO `persons_test` VALUES ("252", "Мешель", "Мешель");
INSERT INTO `persons_test` VALUES ("253", "Мигаловский К. А.", "Мигаловский К. А.");
INSERT INTO `persons_test` VALUES ("254", "Мижуев К.", "Мижуев К.");
INSERT INTO `persons_test` VALUES ("255", "Мизеров М. А.", "Мизеров М. А.");
INSERT INTO `persons_test` VALUES ("256", "Миницкий С. И.", "Миницкий С. И.");
INSERT INTO `persons_test` VALUES ("257", "Миронков А.", "Миронков А.");
INSERT INTO `persons_test` VALUES ("258", "Мнацаканов Г. С.", "Мнацаканов Г. С.");
INSERT INTO `persons_test` VALUES ("259", "Морозов М.", "Морозов М.");
INSERT INTO `persons_test` VALUES ("260", "Нарин В. Н.", "Нарин В. Н.");
INSERT INTO `persons_test` VALUES ("261", "Нафанаил (архимандрит)", "Нафанаил (архимандрит)");
INSERT INTO `persons_test` VALUES ("262", "Небольсин", "Небольсин");
INSERT INTO `persons_test` VALUES ("263", "Немирович-Данченко Г. А.", "Немирович-Данченко Г. А.");
INSERT INTO `persons_test` VALUES ("264", "нет", "нет");
INSERT INTO `persons_test` VALUES ("265", "Никифоров Е.", "Никифоров Е.");
INSERT INTO `persons_test` VALUES ("266", "Никольский В.", "Никольский В.");
INSERT INTO `persons_test` VALUES ("267", "Нобель Л.", "Нобель Л.");
INSERT INTO `persons_test` VALUES ("268", "Носов М. Н.", "Носов М. Н.");
INSERT INTO `persons_test` VALUES ("269", "Нюгрен К.", "Нюгрен К.");
INSERT INTO `persons_test` VALUES ("270", "Нярвяйнен И. С.", "Нярвяйнен И. С.");
INSERT INTO `persons_test` VALUES ("271", "Озеров", "Озеров");
INSERT INTO `persons_test` VALUES ("272", "Окуньков С. Г.", "Окуньков С. Г.");
INSERT INTO `persons_test` VALUES ("273", "Ольга Константиновна (королева)", "Ольга Константиновна (королева)");
INSERT INTO `persons_test` VALUES ("274", "ольхин", "Ольхин");
INSERT INTO `persons_test` VALUES ("275", "Островский А. Г.", "Островский А. Г.");
INSERT INTO `persons_test` VALUES ("276", "Охотин В.", "Охотин В.");
INSERT INTO `persons_test` VALUES ("277", "Охотин К. П.", "Охотин К. П.");
INSERT INTO `persons_test` VALUES ("278", "Ошевенский", "Ошевенский");
INSERT INTO `persons_test` VALUES ("279", "Павел (Доброхотов)", "Павел (Доброхотов)");
INSERT INTO `persons_test` VALUES ("280", "Павлов А. П.", "Павлов А. П.");
INSERT INTO `persons_test` VALUES ("281", "Павлов П. П.", "Павлов П. П.");
INSERT INTO `persons_test` VALUES ("282", "Павловский А.", "Павловский А.");
INSERT INTO `persons_test` VALUES ("283", "Падорин А. (Крузе Б.)", "Падорин А. (Крузе Б.)");
INSERT INTO `persons_test` VALUES ("284", "Палибин А.", "Палибин А.");
INSERT INTO `persons_test` VALUES ("285", "Пантелеев С. П.", "Пантелеев С. П.");
INSERT INTO `persons_test` VALUES ("286", "Парамошков Г. Г.", "Парамошков Г. Г.");
INSERT INTO `persons_test` VALUES ("287", "Парфенов В. М.", "Парфенов В. М.");
INSERT INTO `persons_test` VALUES ("288", "Педдер А. Ю.", "Педдер А. Ю.");
INSERT INTO `persons_test` VALUES ("289", "Пекарская", "Пекарская");
INSERT INTO `persons_test` VALUES ("290", "Пекшуев", "Пекшуев");
INSERT INTO `persons_test` VALUES ("291", "Перфильев К. Н.", "Перфильев К. Н.");
INSERT INTO `persons_test` VALUES ("292", "Петров", "Петров");
INSERT INTO `persons_test` VALUES ("293", "Петров Н. В.", "Петров Н. В.");
INSERT INTO `persons_test` VALUES ("294", "Петтай В. Л.", "Петтай В. Л.");
INSERT INTO `persons_test` VALUES ("295", "Петухов", "Петухов");
INSERT INTO `persons_test` VALUES ("296", "Пешаков И.", "Пешаков И.");
INSERT INTO `persons_test` VALUES ("297", "Пикин М. П.", "Пикин М. П.");
INSERT INTO `persons_test` VALUES ("298", "Пикин Н. Ф.", "Пикин Н. Ф.");
INSERT INTO `persons_test` VALUES ("299", "Пилко Н. Ф.", "Пилко Н. Ф.");
INSERT INTO `persons_test` VALUES ("300", "Пименов Г. Е.", "Пименов Г. Е.");
INSERT INTO `persons_test` VALUES ("301", "Пименов Е. Г.", "Пименов Е. Г.");
INSERT INTO `persons_test` VALUES ("302", "Пименова А. Н.", "Пименова А. Н.");
INSERT INTO `persons_test` VALUES ("303", "Пипирас А. Д.", "Пипирас А. Д.");
INSERT INTO `persons_test` VALUES ("304", "Пира", "Пира Ла Д.");
INSERT INTO `persons_test` VALUES ("305", "Плесская А. Я.", "Плесская А. Я.");
INSERT INTO `persons_test` VALUES ("306", "Подкопаев", "Подкопаев");
INSERT INTO `persons_test` VALUES ("307", "Попов А. Ф.", "Попов А. Ф.");
INSERT INTO `persons_test` VALUES ("308", "Попов Н. М.", "Попов Н. М.");
INSERT INTO `persons_test` VALUES ("309", "Постельников", "Плесская А. Я.");
INSERT INTO `persons_test` VALUES ("310", "Постоянов В. В.", "Постоянов В. В.");
INSERT INTO `persons_test` VALUES ("311", "Правдин И. Ф.", "Правдин И. Ф.");
INSERT INTO `persons_test` VALUES ("312", "Правдин М. Н.", "Правдин М. Н.");
INSERT INTO `persons_test` VALUES ("313", "Преженцов А. П.", "Преженцов А. П.");
INSERT INTO `persons_test` VALUES ("314", "Прокконен П. С.", "Прокконен П. С.");
INSERT INTO `persons_test` VALUES ("315", "Протасьев Н. В.", "Протасьев Н. В.");
INSERT INTO `persons_test` VALUES ("316", "Прохоров В. Д.", "Прохоров В. Д.");
INSERT INTO `persons_test` VALUES ("317", "прохоров И. Ф.", "Прохоров И. Ф.");
INSERT INTO `persons_test` VALUES ("318", "Прохоров Ф. И.", "Прохоров Ф. И.");
INSERT INTO `persons_test` VALUES ("319", "Прушевский В. Р.", "Прушевский В. Р.");
INSERT INTO `persons_test` VALUES ("320", "Путин В. В.", "Путин В. В.");
INSERT INTO `persons_test` VALUES ("321", "Путята В. А.", "Путята В. А.");
INSERT INTO `persons_test` VALUES ("322", "Пущин И. П.", "Пущин И. П.");
INSERT INTO `persons_test` VALUES ("323", "Рассветов Л.", "Рассветов Л.");
INSERT INTO `persons_test` VALUES ("324", "Ратник К. К.", "Ратник К. К.");
INSERT INTO `persons_test` VALUES ("325", "Ребовский М. Е.", "Ребовский М. Е.");
INSERT INTO `persons_test` VALUES ("326", "Рейнонен Э. Э.", "Рейнонен Э. Э.");
INSERT INTO `persons_test` VALUES ("327", "Рейхардт", "Рейхардт");
INSERT INTO `persons_test` VALUES ("328", "Рейхенбах", "Рейхенбах");
INSERT INTO `persons_test` VALUES ("329", "Рекс Т.", "Рекс Т.");
INSERT INTO `persons_test` VALUES ("330", "Рогов Г.", "Рогов Г.");
INSERT INTO `persons_test` VALUES ("331", "Рогозин В. А.", "Рогозин В. А.");
INSERT INTO `persons_test` VALUES ("332", "Рожнов", "Рожнов");
INSERT INTO `persons_test` VALUES ("333", "Розенштандт Г.", "Розенштандт Г.");
INSERT INTO `persons_test` VALUES ("334", "Романов Н.", "Романов Н.");
INSERT INTO `persons_test` VALUES ("335", "Романов С.", "Романов С.");
INSERT INTO `persons_test` VALUES ("336", "Рудницкий А. М.", "Рудницкий А. М.");
INSERT INTO `persons_test` VALUES ("337", "Русаков П. А.", "Русаков П. А.");
INSERT INTO `persons_test` VALUES ("338", "Русаокв А. А.", "Русаков А. А.");
INSERT INTO `persons_test` VALUES ("339", "Рыбин Ф. С.", "Рыбин Ф. С.");
INSERT INTO `persons_test` VALUES ("340", "Рябоевы", "Рябоевы");
INSERT INTO `persons_test` VALUES ("341", "Саареля К. А.", "Саареля К. А.");
INSERT INTO `persons_test` VALUES ("342", "Саблин", "Саблин");
INSERT INTO `persons_test` VALUES ("343", "Савинов", "Савинов");
INSERT INTO `persons_test` VALUES ("344", "Сарычев А. Т.", "Сарычев А. Т.");
INSERT INTO `persons_test` VALUES ("345", "Селиверстов М.", "Селиверстов М.");
INSERT INTO `persons_test` VALUES ("346", "Семенов А.", "Семенов А.");
INSERT INTO `persons_test` VALUES ("347", "Семенов А. С.", "Семенов А. С.");
INSERT INTO `persons_test` VALUES ("348", "Сергеев И. И. (Иоанн Кронштадтский)", "Сергеев И. И. (Иоанн Кронштадтский)");
INSERT INTO `persons_test` VALUES ("349", "Сетеля Э. Н.", "Сетеля Э. Н.");
INSERT INTO `persons_test` VALUES ("350", "Сигов В. П.", "Сигов В. П.");
INSERT INTO `persons_test` VALUES ("351", "Сидоренко В. В.", "Сидоренко В. В.");
INSERT INTO `persons_test` VALUES ("352", "Симанов С.", "Симанов С.");
INSERT INTO `persons_test` VALUES ("353", "Синисало Г.-Р. Н.", "Синисало Г.-Р. Н.");
INSERT INTO `persons_test` VALUES ("354", "Синцов М. А.", "Синцов М. А.");
INSERT INTO `persons_test` VALUES ("355", "Славинский К. П.", "Славинский К. П.");
INSERT INTO `persons_test` VALUES ("356", "Слепцов А. Ф.", "Слепцов А. Ф.");
INSERT INTO `persons_test` VALUES ("357", "Смирнов И. В.", "Смирнов И. В.");
INSERT INTO `persons_test` VALUES ("358", "Смоликова А. А.", "Смоликова А. А.");
INSERT INTO `persons_test` VALUES ("359", "Смоликова Е. К.", "Смоликова Е. К.");
INSERT INTO `persons_test` VALUES ("360", "Смотрич", "Смотрич");
INSERT INTO `persons_test` VALUES ("361", "Собчак М. Я.", "Собчак М. Я.");
INSERT INTO `persons_test` VALUES ("362", "Соколова Е. Т.", "Соколова Е. Т.");
INSERT INTO `persons_test` VALUES ("363", "Сольберг Ф. Г.", "Сольберг Ф. Г.");
INSERT INTO `persons_test` VALUES ("364", "Сотикова А. Н.", "Сотикова А. Н.");
INSERT INTO `persons_test` VALUES ("365", "Спадаренков П.", "Спадаренков П.");
INSERT INTO `persons_test` VALUES ("366", "Сретенский Е. С.", "Сретенский Е. С.");
INSERT INTO `persons_test` VALUES ("367", "Ставропуло Н.", "Ставропуло Н.");
INSERT INTO `persons_test` VALUES ("368", "Стенберг Э.", "Стенберг Э.");
INSERT INTO `persons_test` VALUES ("369", "Стручков Н. С.", "Стручков Н. С.");
INSERT INTO `persons_test` VALUES ("370", "Студитов П. В.", "Студитов П. В.");
INSERT INTO `persons_test` VALUES ("371", "Сулимейко", "Сулимейко");
INSERT INTO `persons_test` VALUES ("372", "Суханов", "Суханов");
INSERT INTO `persons_test` VALUES ("373", "Сухонкин В.", "Сухонкин В.");
INSERT INTO `persons_test` VALUES ("374", "Табарданова Г. А.", "Табарданова Г. А.");
INSERT INTO `persons_test` VALUES ("375", "Танасейчук Г. Я.", "Танасейчук Г. Я.");
INSERT INTO `persons_test` VALUES ("376", "Таратайкин Г. В.", "Таратайкин Г. В.");
INSERT INTO `persons_test` VALUES ("377", "Тарле Ц. Д.", "Тарле Ц. Д.");
INSERT INTO `persons_test` VALUES ("378", "Теребухин", "Теребухин");
INSERT INTO `persons_test` VALUES ("379", "Тетерников Ф. К.", "Тетерников Ф. К.");
INSERT INTO `persons_test` VALUES ("380", "Тимофеев", "Тимофеев");
INSERT INTO `persons_test` VALUES ("381", "Тимошин Н. М.", "Тимошин Н. М.");
INSERT INTO `persons_test` VALUES ("382", "Титов Алексей Иванович", "Титов Алексей Иванович");
INSERT INTO `persons_test` VALUES ("383", "Титов П.", "Титов П.");
INSERT INTO `persons_test` VALUES ("384", "Тихонов И. Ф.", "Тихонов И. Ф.");
INSERT INTO `persons_test` VALUES ("385", "Торшилова М.", "Торшилова М.");
INSERT INTO `persons_test` VALUES ("386", "Троцкая К.", "Троцкая К.");
INSERT INTO `persons_test` VALUES ("387", "Тулин Д. И.", "Тулин Д. И.");
INSERT INTO `persons_test` VALUES ("388", "Тутолмин Т. И.", "Тутолмин Т. И.");
INSERT INTO `persons_test` VALUES ("389", "Ураев Р. Ф.", "Ураев Р. Ф.");
INSERT INTO `persons_test` VALUES ("390", "Успенский В. Л.", "Успенский В. Л.");
INSERT INTO `persons_test` VALUES ("391", "Федоров", "Федоров");
INSERT INTO `persons_test` VALUES ("392", "Федоров Ф.", "Федоров Ф.");
INSERT INTO `persons_test` VALUES ("393", "Фепонов Н. М.", "Фепонов Н. М.");
INSERT INTO `persons_test` VALUES ("394", "Флигельман", "Флигельман");
INSERT INTO `persons_test` VALUES ("395", "Флодерус Б.", "Флодерус Б.");
INSERT INTO `persons_test` VALUES ("396", "Фогель Ф. Ф.", "Фогель Ф. Ф.");
INSERT INTO `persons_test` VALUES ("397", "Форкейн", "Форкейн");
INSERT INTO `persons_test` VALUES ("398", "Франц Р. Я.", "Франц Р. Я.");
INSERT INTO `persons_test` VALUES ("399", "Фрибес В. Ф.", "Фрибес В. Ф.");
INSERT INTO `persons_test` VALUES ("400", "Фридриксен Л.", "Фридриксен Л.");
INSERT INTO `persons_test` VALUES ("401", "Фридрихсон А. И.", "Фридрихсон А. И.");
INSERT INTO `persons_test` VALUES ("402", "Фролов Б. Г.", "Фролов Б. Г.");
INSERT INTO `persons_test` VALUES ("403", "Фурсов В.", "Фурсов В.");
INSERT INTO `persons_test` VALUES ("404", "Харламов Б. В.", "Харламов Б. В.");
INSERT INTO `persons_test` VALUES ("405", "Харькин Г. С.", "Харькин Г. С.");
INSERT INTO `persons_test` VALUES ("406", "Хлебников С. А.", "Хлебников С. А.");
INSERT INTO `persons_test` VALUES ("407", "Ходотов", "Ходотов");
INSERT INTO `persons_test` VALUES ("408", "Холодный М. П.", "Холодный М. П.");
INSERT INTO `persons_test` VALUES ("409", "Холодный П. Я.", "Холодный П. Я.");
INSERT INTO `persons_test` VALUES ("410", "Хорошнев Н.", "Хорошнев Н.");
INSERT INTO `persons_test` VALUES ("411", "Хультен Э.", "Хультен Э.");
INSERT INTO `persons_test` VALUES ("412", "Хумек Г. И.", "Хумек Г. И.");
INSERT INTO `persons_test` VALUES ("413", "Цвиллинг И. И.", "Цвиллинг И. И.");
INSERT INTO `persons_test` VALUES ("414", "Цибулькин Н. Н.", "Цибулькин Н. Н.");
INSERT INTO `persons_test` VALUES ("415", "Цинзерлинг Ю. Д.", "Цинзерлинг Ю. Д.");
INSERT INTO `persons_test` VALUES ("416", "Цолан И. И.", "Цолан И. И.");
INSERT INTO `persons_test` VALUES ("417", "Цолнер Ф. Ф.", "Цолнер Ф. Ф.");
INSERT INTO `persons_test` VALUES ("418", "Цумалья", "Цумалья де П.");
INSERT INTO `persons_test` VALUES ("419", "Чеботарев В. П.", "Чеботарев В. П.");
INSERT INTO `persons_test` VALUES ("420", "Чепаков П.", "Чепаков П.");
INSERT INTO `persons_test` VALUES ("421", "Чертов К. А.", "Чертов К. А.");
INSERT INTO `persons_test` VALUES ("422", "Чильман А. О.", "Чильман А. О.");
INSERT INTO `persons_test` VALUES ("423", "Чудинов Л. П.", "Чудинов Л. П.");
INSERT INTO `persons_test` VALUES ("424", "Чудинов П.", "Чудинов П.");
INSERT INTO `persons_test` VALUES ("425", "Чужинов И. П.", "Чужинов И. П.");
INSERT INTO `persons_test` VALUES ("426", "Шалопанов А. П.", "Шалопанов А. П.");
INSERT INTO `persons_test` VALUES ("427", "Шамец И. К.", "Шамец И. К.");
INSERT INTO `persons_test` VALUES ("428", "Шанин", "Шанин");
INSERT INTO `persons_test` VALUES ("429", "Шаноний Д.", "Шаноний Д.");
INSERT INTO `persons_test` VALUES ("430", "Шапошников П.", "Шапошников П.");
INSERT INTO `persons_test` VALUES ("431", "Швидко Л. А.", "Швидко Л. А.");
INSERT INTO `persons_test` VALUES ("432", "Шегельман И. Р.", "Шегельман И. Р.");
INSERT INTO `persons_test` VALUES ("433", "Шежемский С. В.", "Шежемский С. В.");
INSERT INTO `persons_test` VALUES ("434", "Шелюков Ф. С.", "Шелюков Ф. С.");
INSERT INTO `persons_test` VALUES ("435", "Шершед А.", "Шершед А.");
INSERT INTO `persons_test` VALUES ("436", "Шехирин С. И.", "Шехирин С. И.");
INSERT INTO `persons_test` VALUES ("437", "Шехирина Н. И.", "Шехирина Н. И.");
INSERT INTO `persons_test` VALUES ("438", "Шипилин", "Шипилин");
INSERT INTO `persons_test` VALUES ("439", "Ширипин М. Е.", "Ширипин М. Е.");
INSERT INTO `persons_test` VALUES ("440", "Шихалев Ф. М.", "Шихалев Ф. М.");
INSERT INTO `persons_test` VALUES ("441", "Шишов А. Н.", "Шишов А. Н.");
INSERT INTO `persons_test` VALUES ("442", "Шишов Е. Н.", "Шишов Е. Н.");
INSERT INTO `persons_test` VALUES ("443", "Шкурбало В. М.", "Шкурбало В. М.");
INSERT INTO `persons_test` VALUES ("444", "Шмейс", "Шмейс");
INSERT INTO `persons_test` VALUES ("445", "Шмидт Я. К.", "Шмидт Я. К.");
INSERT INTO `persons_test` VALUES ("446", "Штейнзат Е. С.", "Штейнзат Е. С.");
INSERT INTO `persons_test` VALUES ("447", "Шубников", "Шубников");
INSERT INTO `persons_test` VALUES ("448", "Щелкунов", "Щелкунов");
INSERT INTO `persons_test` VALUES ("449", "Эльснер", "Эльснер");
INSERT INTO `persons_test` VALUES ("450", "Эркко Ю. Ю.", "Эркко Ю. Ю.");
INSERT INTO `persons_test` VALUES ("451", "Ягор Ж. К.", "Ягор Ж. К.");
INSERT INTO `persons_test` VALUES ("452", "Ярышев", "Ярышев");
INSERT INTO `persons_test` VALUES ("453", "Яскунов С. М.", "Яскунов С. М.");
INSERT INTO `persons_test` VALUES ("454", "Ястребов А.", "Ястребов А.");
INSERT INTO `persons_test` VALUES ("455", "Ятцеров П. Г.", "Ятцеров П. Г.");
