INSERT INTO `persons` VALUES ("1","Абросимов П. П.","","9");
INSERT INTO `persons` VALUES ("2","Авзотис Г.","","9");
INSERT INTO `persons` VALUES ("3","Аглицкий Г. А.","","9");
INSERT INTO `persons` VALUES ("4","Агню Д.","","9");
INSERT INTO `persons` VALUES ("5","Адамович С. М.","","9");
INSERT INTO `persons` VALUES ("6","Александров","","9");
INSERT INTO `persons` VALUES ("7","Алешин","","9");
INSERT INTO `persons` VALUES ("8","Алешина А. Б.","","9");
INSERT INTO `persons` VALUES ("9","Альперович Б. С.","","9");
INSERT INTO `persons` VALUES ("10","Альшванг А. А.","","9");
INSERT INTO `persons` VALUES ("11","Андреев Н.","","9");
INSERT INTO `persons` VALUES ("12","Андреев С.","","9");
INSERT INTO `persons` VALUES ("13","Андреева Н.","","9");
INSERT INTO `persons` VALUES ("14","Андрианов Н. Н.","","9");
INSERT INTO `persons` VALUES ("15","Антоновский","","9");
INSERT INTO `persons` VALUES ("16","Аргатов И. И.","","9");
INSERT INTO `persons` VALUES ("17","Аркадий (Федоров)","","9");
INSERT INTO `persons` VALUES ("18","Арсеньев Ю. К.","","9");
INSERT INTO `persons` VALUES ("19","Архипова П. Е.","","9");
INSERT INTO `persons` VALUES ("20","Афанасьев А. А.","","9");
INSERT INTO `persons` VALUES ("21","Базегский П. И.","","9");
INSERT INTO `persons` VALUES ("22","Байков Ф.","","9");
INSERT INTO `persons` VALUES ("23","Бакланов Ю. П.","","9");
INSERT INTO `persons` VALUES ("24","Баландин Т. В.","","9");
INSERT INTO `persons` VALUES ("25","Баралл П.","","9");
INSERT INTO `persons` VALUES ("26","Баранов Д. О.","","9");
INSERT INTO `persons` VALUES ("27","Баранцов А. П.","","9");
INSERT INTO `persons` VALUES ("28","Барбашин В. Б.","","9");
INSERT INTO `persons` VALUES ("29","Басинский","","9");
INSERT INTO `persons` VALUES ("30","Башев П. А.","","9");
INSERT INTO `persons` VALUES ("31","Башева А. М.","","9");
INSERT INTO `persons` VALUES ("32","Белиловский К. А.","","9");
INSERT INTO `persons` VALUES ("33","Беляев А. П.","","9");
INSERT INTO `persons` VALUES ("34","Беляев И. С.","","9");
INSERT INTO `persons` VALUES ("35","Беляков С. М.","","9");
INSERT INTO `persons` VALUES ("36","Бенкендорф А. Х.","","9");
INSERT INTO `persons` VALUES ("37","Березин","","9");
INSERT INTO `persons` VALUES ("38","Бесов","","9");
INSERT INTO `persons` VALUES ("39","Беспальчев А. Ф.","","9");
INSERT INTO `persons` VALUES ("40","Благородченков","","9");
INSERT INTO `persons` VALUES ("41","Блау","","9");
INSERT INTO `persons` VALUES ("42","Блок А. А.","","9");
INSERT INTO `persons` VALUES ("43","Бобринский А. А.","","9");
INSERT INTO `persons` VALUES ("44","Богданов В.","","9");
INSERT INTO `persons` VALUES ("45","Богданов В. Н.","","9");
INSERT INTO `persons` VALUES ("46","Богданов М.","","9");
INSERT INTO `persons` VALUES ("47","Богданов П.","","9");
INSERT INTO `persons` VALUES ("48","Болотников И. М.","","9");
INSERT INTO `persons` VALUES ("49","Большаков И. П.","","9");
INSERT INTO `persons` VALUES ("50","Бонбин П.","","9");
INSERT INTO `persons` VALUES ("51","Бржеский В. Ч.","","9");
INSERT INTO `persons` VALUES ("52","Бронштейн А. Л.","","9");
INSERT INTO `persons` VALUES ("53","Вавилов Г. А.","","9");
INSERT INTO `persons` VALUES ("54","Вагнер","","9");
INSERT INTO `persons` VALUES ("55","Валентик И. Я.","","9");
INSERT INTO `persons` VALUES ("56","Варзугин Н. П.","","9");
INSERT INTO `persons` VALUES ("57","Вашингтон Д.","","9");
INSERT INTO `persons` VALUES ("58","Введенский А. И.","","9");
INSERT INTO `persons` VALUES ("59","Венберг М.","","9");
INSERT INTO `persons` VALUES ("60","Венустов В.","","9");
INSERT INTO `persons` VALUES ("61","Вержбицкий","","9");
INSERT INTO `persons` VALUES ("62","Вилларский","","9");
INSERT INTO `persons` VALUES ("63","Вильчевский Э.","","9");
INSERT INTO `persons` VALUES ("64","Владимир Александрович (великий князь)","","9");
INSERT INTO `persons` VALUES ("65","Власов С.","","9");
INSERT INTO `persons` VALUES ("66","Воздвиженский В.","","9");
INSERT INTO `persons` VALUES ("67","Волейко В. Ф.","","9");
INSERT INTO `persons` VALUES ("68","Волков","","9");
INSERT INTO `persons` VALUES ("69","Володзко Г. Ю.","","9");
INSERT INTO `persons` VALUES ("70","Воронов В. Ф.","","9");
INSERT INTO `persons` VALUES ("71","Воронов Ф. В.","","9");
INSERT INTO `persons` VALUES ("72","Воскресенский А.","","9");
INSERT INTO `persons` VALUES ("73","Воскресенский В.","","9");
INSERT INTO `persons` VALUES ("74","Воскресенский П. А.","","9");
INSERT INTO `persons` VALUES ("75","Вяземский С. А.","","9");
INSERT INTO `persons` VALUES ("76","Гаврилов П. И.","","9");
INSERT INTO `persons` VALUES ("77","Гайдебуров П. П.","","9");
INSERT INTO `persons` VALUES ("78","Галченко","","9");
INSERT INTO `persons` VALUES ("79","Гарш А. Ф.","","9");
INSERT INTO `persons` VALUES ("80","Гарязин А. Л.","","9");
INSERT INTO `persons` VALUES ("81","Герасим (Ионин)","","9");
INSERT INTO `persons` VALUES ("82","Герцев А. И.","","9");
INSERT INTO `persons` VALUES ("83","Гершанович Д. Г.","","9");
INSERT INTO `persons` VALUES ("84","Гиппиев Н. Г. (Лайне Н.)","","9");
INSERT INTO `persons` VALUES ("85","Глиноецкий Г. П.","","9");
INSERT INTO `persons` VALUES ("86","Глушковский Ю. В.","","9");
INSERT INTO `persons` VALUES ("87","Голубева Г.","","9");
INSERT INTO `persons` VALUES ("88","Гончаревский А. К.","","9");
INSERT INTO `persons` VALUES ("89","Готман М. Ф.","","9");
INSERT INTO `persons` VALUES ("90","Грамицарис А.","","9");
INSERT INTO `persons` VALUES ("91","Граммати Е. Е.","","9");
INSERT INTO `persons` VALUES ("92","Грибанов В. В.","","9");
INSERT INTO `persons` VALUES ("93","Григорьев Г. Г.","","9");
INSERT INTO `persons` VALUES ("94","Григорьева Е. С.","","9");
INSERT INTO `persons` VALUES ("95","Громов И. Ф.","","9");
INSERT INTO `persons` VALUES ("96","Громов П.","","9");
INSERT INTO `persons` VALUES ("97","Гручин М. И.","","9");
INSERT INTO `persons` VALUES ("98","Гюнтер К. К.","","9");
INSERT INTO `persons` VALUES ("99","Данилов Т.","","9");
INSERT INTO `persons` VALUES ("100","Дашков А. В.","","9");
INSERT INTO `persons` VALUES ("101","Дворжицкий К. А.","","9");
INSERT INTO `persons` VALUES ("102","Девяткин В. В.","","9");
INSERT INTO `persons` VALUES ("103","Дейхман Я. П.","","9");
INSERT INTO `persons` VALUES ("104","Де-Ливрон А. А.","","9");
INSERT INTO `persons` VALUES ("105","Дементьев П. В.","","9");
INSERT INTO `persons` VALUES ("106","Денисова А. Ф.","","9");
INSERT INTO `persons` VALUES ("107","Дингельштедт Ф.","","9");
INSERT INTO `persons` VALUES ("108","Добре К.","","9");
INSERT INTO `persons` VALUES ("109","Докучаев-Басков К. А.","","9");
INSERT INTO `persons` VALUES ("110","Долгов И.","","9");
INSERT INTO `persons` VALUES ("111","Дорофеев Я.","","9");
INSERT INTO `persons` VALUES ("112","Драницын","","9");
INSERT INTO `persons` VALUES ("113","Друзин М. М.","","9");
INSERT INTO `persons` VALUES ("114","Дуденков В. Д.","","9");
INSERT INTO `persons` VALUES ("115","Дункен","","9");
INSERT INTO `persons` VALUES ("116","Дыклоп Э. П.","","9");
INSERT INTO `persons` VALUES ("117","Дюливье Е. Н.","","9");
INSERT INTO `persons` VALUES ("118","Егоров Г. Ф.","","9");
INSERT INTO `persons` VALUES ("119","Елнинский Н. И.","","9");
INSERT INTO `persons` VALUES ("120","Ерошкин.","","9");
INSERT INTO `persons` VALUES ("121","Ершов С. А.","","9");
INSERT INTO `persons` VALUES ("122","Ефимов А. М.","","9");
INSERT INTO `persons` VALUES ("123","Ефимов С. В.","","9");
INSERT INTO `persons` VALUES ("124","Жеребцов","","9");
INSERT INTO `persons` VALUES ("125","Жигарев П. Ф.","","9");
INSERT INTO `persons` VALUES ("126","Жилинская Е. К.","","9");
INSERT INTO `persons` VALUES ("127","Заводовский М. Н.","","9");
INSERT INTO `persons` VALUES ("128","Загонский Е. К.","","9");
INSERT INTO `persons` VALUES ("129","Зайцев В. М.","","9");
INSERT INTO `persons` VALUES ("130","Зайцев С. В.","","9");
INSERT INTO `persons` VALUES ("131","Закревская Е. М.","","9");
INSERT INTO `persons` VALUES ("132","Заозерский В.","","9");
INSERT INTO `persons` VALUES ("133","Звероловлев Е.","","9");
INSERT INTO `persons` VALUES ("134","Звероловлев Т. А.","","9");
INSERT INTO `persons` VALUES ("135","Золотухин Е. О.","","9");
INSERT INTO `persons` VALUES ("136","Зон А. А.","","9");
INSERT INTO `persons` VALUES ("137","Зубовский М. И.","","9");
INSERT INTO `persons` VALUES ("138","Зубравский К. Ф.","","9");
INSERT INTO `persons` VALUES ("139","Зюльмаев Г.","","9");
INSERT INTO `persons` VALUES ("140","Иванов Г.","","9");
INSERT INTO `persons` VALUES ("141","Иванов М.","","9");
INSERT INTO `persons` VALUES ("142","Иванов Н. П.","","9");
INSERT INTO `persons` VALUES ("143","Ивановский","","9");
INSERT INTO `persons` VALUES ("144","Ивановский Ю.","","9");
INSERT INTO `persons` VALUES ("145","Игнатович Т.","","9");
INSERT INTO `persons` VALUES ("146","Иевлев Д. П.","","9");
INSERT INTO `persons` VALUES ("147","Иннокентий (Левизор)","","9");
INSERT INTO `persons` VALUES ("148","Иоанникий (казначей Соловецкого монастыря)","","9");
INSERT INTO `persons` VALUES ("149","Иогансон К. А.","","9");
INSERT INTO `persons` VALUES ("150","Ионафан (Руднев)","","9");
INSERT INTO `persons` VALUES ("151","Исихий (Звероловлев)","","9");
INSERT INTO `persons` VALUES ("152","Июдин И. М.","","9");
INSERT INTO `persons` VALUES ("153","Июдин Ф. Е.","","9");
INSERT INTO `persons` VALUES ("154","Калашников К. А.","","9");
INSERT INTO `persons` VALUES ("155","Каликин В. С.","","9");
INSERT INTO `persons` VALUES ("156","Канорская Г. Н.","","9");
INSERT INTO `persons` VALUES ("157","Капица Л. Л.","","9");
INSERT INTO `persons` VALUES ("158","Карп С. М.","","9");
INSERT INTO `persons` VALUES ("159","Карпин А. Б.","","9");
INSERT INTO `persons` VALUES ("160","Карпов","","9");
INSERT INTO `persons` VALUES ("161","Катун Д. И.","","9");
INSERT INTO `persons` VALUES ("162","Кацеблин П. И.","","9");
INSERT INTO `persons` VALUES ("163","Качалов","","9");
INSERT INTO `persons` VALUES ("164","Качалов П. В.","","9");
INSERT INTO `persons` VALUES ("165","Качикис А.","","9");
INSERT INTO `persons` VALUES ("166","Кермик Ф. Х.","","9");
INSERT INTO `persons` VALUES ("167","Кийскинен А. И.","","9");
INSERT INTO `persons` VALUES ("168","Киселев Г. И.","","9");
INSERT INTO `persons` VALUES ("169","Климов А. И.","","9");
INSERT INTO `persons` VALUES ("170","Клодницкий Г. Э.","","9");
INSERT INTO `persons` VALUES ("171","Клоковский З. И.","","9");
INSERT INTO `persons` VALUES ("172","Ключарева А. А.","","9");
INSERT INTO `persons` VALUES ("173","Кобелев П.","","9");
INSERT INTO `persons` VALUES ("174","Ковалевский Л. В.","","9");
INSERT INTO `persons` VALUES ("175","Козлов Т.","","9");
INSERT INTO `persons` VALUES ("176","Козырев И. И.","","9");
INSERT INTO `persons` VALUES ("177","Колмовский Л. Н.","","9");
INSERT INTO `persons` VALUES ("178","Колосенок С. В.","","9");
INSERT INTO `persons` VALUES ("179","Компанеец Д.","","9");
INSERT INTO `persons` VALUES ("180","Коненков С. Т.","","9");
INSERT INTO `persons` VALUES ("181","Коновницын П. П.","","9");
INSERT INTO `persons` VALUES ("182","Кононов Ф.","","9");
INSERT INTO `persons` VALUES ("183","Кораблев А. С.","","9");
INSERT INTO `persons` VALUES ("184","Корндорф А. Ф.","","9");
INSERT INTO `persons` VALUES ("185","Костюк","","9");
INSERT INTO `persons` VALUES ("186","Косцепецкий","","9");
INSERT INTO `persons` VALUES ("187","Краверский А. В.","","9");
INSERT INTO `persons` VALUES ("188","Кравченко А. И.","","9");
INSERT INTO `persons` VALUES ("189","Кратц К. О.","","9");
INSERT INTO `persons` VALUES ("190","Кретковский К. Ф.","","9");
INSERT INTO `persons` VALUES ("191","Кридин П. В.","","9");
INSERT INTO `persons` VALUES ("192","Кротова Н. А.","","9");
INSERT INTO `persons` VALUES ("193","Крохина","","9");
INSERT INTO `persons` VALUES ("194","Крутяков П. И.","","9");
INSERT INTO `persons` VALUES ("195","Крылов А. Я.","","9");
INSERT INTO `persons` VALUES ("196","Крылов Н. М.","","9");
INSERT INTO `persons` VALUES ("197","Кубагин И","","9");
INSERT INTO `persons` VALUES ("198","Кудряшов А. П.","","9");
INSERT INTO `persons` VALUES ("199","Кузьмин","","9");
INSERT INTO `persons` VALUES ("200","Кузьмин А. Ф.","","9");
INSERT INTO `persons` VALUES ("201","Куликовский Г. И.","","9");
INSERT INTO `persons` VALUES ("202","Куткевич А. И.","","9");
INSERT INTO `persons` VALUES ("203","Кутузов А. А.","","9");
INSERT INTO `persons` VALUES ("204","Кутузов М. Ф.","","9");
INSERT INTO `persons` VALUES ("205","Лаварелло М.","","9");
INSERT INTO `persons` VALUES ("206","Лавров","","9");
INSERT INTO `persons` VALUES ("207","Ланговой С. В.","","9");
INSERT INTO `persons` VALUES ("208","Лачинов","","9");
INSERT INTO `persons` VALUES ("209","Левенштейн М. С.","","9");
INSERT INTO `persons` VALUES ("210","Леви","","9");
INSERT INTO `persons` VALUES ("211","Леви М. Ф.","","9");
INSERT INTO `persons` VALUES ("212","Левин Л. Г.","","9");
INSERT INTO `persons` VALUES ("213","Лежиев","","9");
INSERT INTO `persons` VALUES ("214","Лемсен М.","","9");
INSERT INTO `persons` VALUES ("215","Ленин Н. В.","","9");
INSERT INTO `persons` VALUES ("216","Ли Ки Ву","","9");
INSERT INTO `persons` VALUES ("217","Линдгрен А.","","9");
INSERT INTO `persons` VALUES ("218","Липкин","","9");
INSERT INTO `persons` VALUES ("219","Логинов","","9");
INSERT INTO `persons` VALUES ("220","Лузгин В. Н.","","9");
INSERT INTO `persons` VALUES ("221","Лукас Д.","","9");
INSERT INTO `persons` VALUES ("222","Лукин И. С.","","9");
INSERT INTO `persons` VALUES ("223","Лукс К. И.","","9");
INSERT INTO `persons` VALUES ("224","Львов","","9");
INSERT INTO `persons` VALUES ("225","Любовина М. Н.","","9");
INSERT INTO `persons` VALUES ("226","Лядинский Н. П.","","9");
INSERT INTO `persons` VALUES ("227","Мазуровский Л. А.","","9");
INSERT INTO `persons` VALUES ("228","Майстерман С. А.","","9");
INSERT INTO `persons` VALUES ("229","Макаров Г.","","9");
INSERT INTO `persons` VALUES ("230","Маковская Н. А.","","9");
INSERT INTO `persons` VALUES ("231","Максимов А. П.","","9");
INSERT INTO `persons` VALUES ("232","Максимова М.","","9");
INSERT INTO `persons` VALUES ("233","Максютенко Б. М.","","9");
INSERT INTO `persons` VALUES ("234","Малокрошечный И. И.","","9");
INSERT INTO `persons` VALUES ("235","Маминов И. А.","","9");
INSERT INTO `persons` VALUES ("236","Мареш И. Ф.","","9");
INSERT INTO `persons` VALUES ("237","Марин Н. М.","","9");
INSERT INTO `persons` VALUES ("238","Маркконен Э. В.","","9");
INSERT INTO `persons` VALUES ("239","Марков Г. Н.","","9");
INSERT INTO `persons` VALUES ("240","Мартьянов А.","","9");
INSERT INTO `persons` VALUES ("241","Маттилайнен","","9");
INSERT INTO `persons` VALUES ("242","Мауну","","9");
INSERT INTO `persons` VALUES ("243","Машаров Ф. Ф.","","9");
INSERT INTO `persons` VALUES ("244","Мелик-Шахназаров","","9");
INSERT INTO `persons` VALUES ("245","Мелленберг Э. Ф.","","9");
INSERT INTO `persons` VALUES ("246","Мемнонов В. В.","","9");
INSERT INTO `persons` VALUES ("247","Мензенкампф фон Ю.","","9");
INSERT INTO `persons` VALUES ("248","Меркульев А.","","9");
INSERT INTO `persons` VALUES ("249","Мертенс В. Ф.","","9");
INSERT INTO `persons` VALUES ("250","Мешель","","9");
INSERT INTO `persons` VALUES ("251","Мигаловский К. А.","","9");
INSERT INTO `persons` VALUES ("252","Мижуев К.","","9");
INSERT INTO `persons` VALUES ("253","Мизеров М. А.","","9");
INSERT INTO `persons` VALUES ("254","Миницкий С. И.","","9");
INSERT INTO `persons` VALUES ("255","Миронков А.","","9");
INSERT INTO `persons` VALUES ("256","Мнацаканов Г. С.","","9");
INSERT INTO `persons` VALUES ("257","Морозов М.","","9");
INSERT INTO `persons` VALUES ("258","Нарин В. Н.","","9");
INSERT INTO `persons` VALUES ("259","Нафанаил (архимандрит)","","9");
INSERT INTO `persons` VALUES ("260","Небольсин","","9");
INSERT INTO `persons` VALUES ("261","Немирович-Данченко Г. А.","","9");
INSERT INTO `persons` VALUES ("262","нет","","9");
INSERT INTO `persons` VALUES ("263","Никифоров Е.","","9");
INSERT INTO `persons` VALUES ("264","Никольский В.","","9");
INSERT INTO `persons` VALUES ("265","Нобель Л.","","9");
INSERT INTO `persons` VALUES ("266","Носов М. Н.","","9");
INSERT INTO `persons` VALUES ("267","Нюгрен К.","","9");
INSERT INTO `persons` VALUES ("268","Нярвяйнен И. С.","","9");
INSERT INTO `persons` VALUES ("269","Озеров","","9");
INSERT INTO `persons` VALUES ("270","Окуньков С. Г.","","9");
INSERT INTO `persons` VALUES ("271","Ольга Константиновна (королева)","","9");
INSERT INTO `persons` VALUES ("272","Ольхин","","9");
INSERT INTO `persons` VALUES ("273","Островский А. Г.","","9");
INSERT INTO `persons` VALUES ("274","Охотин В.","","9");
INSERT INTO `persons` VALUES ("275","Охотин К. П.","","9");
INSERT INTO `persons` VALUES ("276","Ошевенский","","9");
INSERT INTO `persons` VALUES ("277","Павел (Доброхотов)","","9");
INSERT INTO `persons` VALUES ("278","Павлов А. П.","","9");
INSERT INTO `persons` VALUES ("279","Павлов П. П.","","9");
INSERT INTO `persons` VALUES ("280","Павловский А.","","9");
INSERT INTO `persons` VALUES ("281","Падорин А. (Крузе Б.)","","9");
INSERT INTO `persons` VALUES ("282","Палибин А.","","9");
INSERT INTO `persons` VALUES ("283","Пантелеев С. П.","","9");
INSERT INTO `persons` VALUES ("284","Парамошков Г. Г.","","9");
INSERT INTO `persons` VALUES ("285","Парфенов В. М.","","9");
INSERT INTO `persons` VALUES ("286","Педдер А. Ю.","","9");
INSERT INTO `persons` VALUES ("287","Пекарская","","9");
INSERT INTO `persons` VALUES ("288","Пекшуев","","9");
INSERT INTO `persons` VALUES ("289","Перфильев К. Н.","","9");
INSERT INTO `persons` VALUES ("290","Петров","","9");
INSERT INTO `persons` VALUES ("291","Петров Н. В.","","9");
INSERT INTO `persons` VALUES ("292","Петтай В. Л.","","9");
INSERT INTO `persons` VALUES ("293","Петухов","","9");
INSERT INTO `persons` VALUES ("294","Пешаков И.","","9");
INSERT INTO `persons` VALUES ("295","Пикин М. П.","","9");
INSERT INTO `persons` VALUES ("296","Пикин Н. Ф.","","9");
INSERT INTO `persons` VALUES ("297","Пилко Н. Ф.","","9");
INSERT INTO `persons` VALUES ("298","Пименов Г. Е.","","9");
INSERT INTO `persons` VALUES ("299","Пименов Е. Г.","","9");
INSERT INTO `persons` VALUES ("300","Пименова А. Н.","","9");
INSERT INTO `persons` VALUES ("301","Пипирас А. Д.","","9");
INSERT INTO `persons` VALUES ("302","Пира Ла Д.","","9");
INSERT INTO `persons` VALUES ("303","Плесская А. Я.","","9");
INSERT INTO `persons` VALUES ("304","Подкопаев","","9");
INSERT INTO `persons` VALUES ("305","Попов А. Ф.","","9");
INSERT INTO `persons` VALUES ("306","Попов Н. М.","","9");
INSERT INTO `persons` VALUES ("307","Постоянов В. В.","","9");
INSERT INTO `persons` VALUES ("308","Правдин И. Ф.","","9");
INSERT INTO `persons` VALUES ("309","Правдин М. Н.","","9");
INSERT INTO `persons` VALUES ("310","Преженцов А. П.","","9");
INSERT INTO `persons` VALUES ("311","Прокконен П. С.","","9");
INSERT INTO `persons` VALUES ("312","Протасьев Н. В.","","9");
INSERT INTO `persons` VALUES ("313","Прохоров В. Д.","","9");
INSERT INTO `persons` VALUES ("314","Прохоров И. Ф.","","9");
INSERT INTO `persons` VALUES ("315","Прохоров Ф. И.","","9");
INSERT INTO `persons` VALUES ("316","Прушевский В. Р.","","9");
INSERT INTO `persons` VALUES ("317","Путин В. В.","","9");
INSERT INTO `persons` VALUES ("318","Путята В. А.","","9");
INSERT INTO `persons` VALUES ("319","Пущин И. П.","","9");
INSERT INTO `persons` VALUES ("320","Рассветов Л.","","9");
INSERT INTO `persons` VALUES ("321","Ратник К. К.","","9");
INSERT INTO `persons` VALUES ("322","Ребовский М. Е.","","9");
INSERT INTO `persons` VALUES ("323","Рейнонен Э. Э.","","9");
INSERT INTO `persons` VALUES ("324","Рейхардт","","9");
INSERT INTO `persons` VALUES ("325","Рейхенбах","","9");
INSERT INTO `persons` VALUES ("326","Рекс Т.","","9");
INSERT INTO `persons` VALUES ("327","Рогов Г.","","9");
INSERT INTO `persons` VALUES ("328","Рогозин В. А.","","9");
INSERT INTO `persons` VALUES ("329","Рожнов","","9");
INSERT INTO `persons` VALUES ("330","Розенштандт Г.","","9");
INSERT INTO `persons` VALUES ("331","Романов Н.","","9");
INSERT INTO `persons` VALUES ("332","Романов С.","","9");
INSERT INTO `persons` VALUES ("333","Рудницкий А. М.","","9");
INSERT INTO `persons` VALUES ("334","Русаков П. А.","","9");
INSERT INTO `persons` VALUES ("335","Русаков А. А.","","9");
INSERT INTO `persons` VALUES ("336","Рыбин Ф. С.","","9");
INSERT INTO `persons` VALUES ("337","Рябоевы","","9");
INSERT INTO `persons` VALUES ("338","Саареля К. А.","","9");
INSERT INTO `persons` VALUES ("339","Саблин","","9");
INSERT INTO `persons` VALUES ("340","Савинов","","9");
INSERT INTO `persons` VALUES ("341","Сарычев А. Т.","","9");
INSERT INTO `persons` VALUES ("342","Селиверстов М.","","9");
INSERT INTO `persons` VALUES ("343","Семенов А.","","9");
INSERT INTO `persons` VALUES ("344","Семенов А. С.","","9");
INSERT INTO `persons` VALUES ("345","Сергеев И. И. (Иоанн Кронштадтский)","","9");
INSERT INTO `persons` VALUES ("346","Сетеля Э. Н.","","9");
INSERT INTO `persons` VALUES ("347","Сигов В. П.","","9");
INSERT INTO `persons` VALUES ("348","Сидоренко В. В.","","9");
INSERT INTO `persons` VALUES ("349","Симанов С.","","9");
INSERT INTO `persons` VALUES ("350","Синисало Г.-Р. Н.","","9");
INSERT INTO `persons` VALUES ("351","Синцов М. А.","","9");
INSERT INTO `persons` VALUES ("352","Славинский К. П.","","9");
INSERT INTO `persons` VALUES ("353","Слепцов А. Ф.","","9");
INSERT INTO `persons` VALUES ("354","Смирнов И. В.","","9");
INSERT INTO `persons` VALUES ("355","Смоликова А. А.","","9");
INSERT INTO `persons` VALUES ("356","Смоликова Е. К.","","9");
INSERT INTO `persons` VALUES ("357","Смотрич","","9");
INSERT INTO `persons` VALUES ("358","Собчак М. Я.","","9");
INSERT INTO `persons` VALUES ("359","Соколова Е. Т.","","9");
INSERT INTO `persons` VALUES ("360","Сольберг Ф. Г.","","9");
INSERT INTO `persons` VALUES ("361","Сотикова А. Н.","","9");
INSERT INTO `persons` VALUES ("362","Спадаренков П.","","9");
INSERT INTO `persons` VALUES ("363","Сретенский Е. С.","","9");
INSERT INTO `persons` VALUES ("364","Ставропуло Н.","","9");
INSERT INTO `persons` VALUES ("365","Стенберг Э.","","9");
INSERT INTO `persons` VALUES ("366","Стручков Н. С.","","9");
INSERT INTO `persons` VALUES ("367","Студитов П. В.","","9");
INSERT INTO `persons` VALUES ("368","Сулимейко","","9");
INSERT INTO `persons` VALUES ("369","Суханов","","9");
INSERT INTO `persons` VALUES ("370","Сухонкин В.","","9");
INSERT INTO `persons` VALUES ("371","Табарданова Г. А.","","9");
INSERT INTO `persons` VALUES ("372","Танасейчук Г. Я.","","9");
INSERT INTO `persons` VALUES ("373","Таратайкин Г. В.","","9");
INSERT INTO `persons` VALUES ("374","Тарле Ц. Д.","","9");
INSERT INTO `persons` VALUES ("375","Теребухин","","9");
INSERT INTO `persons` VALUES ("376","Тетерников Ф. К.","","9");
INSERT INTO `persons` VALUES ("377","Тимофеев","","9");
INSERT INTO `persons` VALUES ("378","Тимошин Н. М.","","9");
INSERT INTO `persons` VALUES ("379","Титов Алексей Иванович","","9");
INSERT INTO `persons` VALUES ("380","Титов П.","","9");
INSERT INTO `persons` VALUES ("381","Тихонов И. Ф.","","9");
INSERT INTO `persons` VALUES ("382","Торшилова М.","","9");
INSERT INTO `persons` VALUES ("383","Троцкая К.","","9");
INSERT INTO `persons` VALUES ("384","Тулин Д. И.","","9");
INSERT INTO `persons` VALUES ("385","Тутолмин Т. И.","","9");
INSERT INTO `persons` VALUES ("386","Ураев Р. Ф.","","9");
INSERT INTO `persons` VALUES ("387","Успенский В. Л.","","9");
INSERT INTO `persons` VALUES ("388","Федоров","","9");
INSERT INTO `persons` VALUES ("389","Федоров Ф.","","9");
INSERT INTO `persons` VALUES ("390","Фепонов Н. М.","","9");
INSERT INTO `persons` VALUES ("391","Флигельман","","9");
INSERT INTO `persons` VALUES ("392","Флодерус Б.","","9");
INSERT INTO `persons` VALUES ("393","Фогель Ф. Ф.","","9");
INSERT INTO `persons` VALUES ("394","Форкейн","","9");
INSERT INTO `persons` VALUES ("395","Франц Р. Я.","","9");
INSERT INTO `persons` VALUES ("396","Фрибес В. Ф.","","9");
INSERT INTO `persons` VALUES ("397","Фридриксен Л.","","9");
INSERT INTO `persons` VALUES ("398","Фридрихсон А. И.","","9");
INSERT INTO `persons` VALUES ("399","Фролов Б. Г.","","9");
INSERT INTO `persons` VALUES ("400","Фурсов В.","","9");
INSERT INTO `persons` VALUES ("401","Харламов Б. В.","","9");
INSERT INTO `persons` VALUES ("402","Харькин Г. С.","","9");
INSERT INTO `persons` VALUES ("403","Хлебников С. А.","","9");
INSERT INTO `persons` VALUES ("404","Ходотов","","9");
INSERT INTO `persons` VALUES ("405","Холодный М. П.","","9");
INSERT INTO `persons` VALUES ("406","Холодный П. Я.","","9");
INSERT INTO `persons` VALUES ("407","Хорошнев Н.","","9");
INSERT INTO `persons` VALUES ("408","Хультен Э.","","9");
INSERT INTO `persons` VALUES ("409","Хумек Г. И.","","9");
INSERT INTO `persons` VALUES ("410","Цвиллинг И. И.","","9");
INSERT INTO `persons` VALUES ("411","Цибулькин Н. Н.","","9");
INSERT INTO `persons` VALUES ("412","Цинзерлинг Ю. Д.","","9");
INSERT INTO `persons` VALUES ("413","Цолан И. И.","","9");
INSERT INTO `persons` VALUES ("414","Цолнер Ф. Ф.","","9");
INSERT INTO `persons` VALUES ("415","Цумалья де П.","","9");
INSERT INTO `persons` VALUES ("416","Чеботарев В. П.","","9");
INSERT INTO `persons` VALUES ("417","Чепаков П.","","9");
INSERT INTO `persons` VALUES ("418","Чертов К. А.","","9");
INSERT INTO `persons` VALUES ("419","Чильман А. О.","","9");
INSERT INTO `persons` VALUES ("420","Чудинов Л. П.","","9");
INSERT INTO `persons` VALUES ("421","Чудинов П.","","9");
INSERT INTO `persons` VALUES ("422","Чужинов И. П.","","9");
INSERT INTO `persons` VALUES ("423","Шалопанов А. П.","","9");
INSERT INTO `persons` VALUES ("424","Шамец И. К.","","9");
INSERT INTO `persons` VALUES ("425","Шанин","","9");
INSERT INTO `persons` VALUES ("426","Шаноний Д.","","9");
INSERT INTO `persons` VALUES ("427","Шапошников П.","","9");
INSERT INTO `persons` VALUES ("428","Швидко Л. А.","","9");
INSERT INTO `persons` VALUES ("429","Шегельман И. Р.","","9");
INSERT INTO `persons` VALUES ("430","Шежемский С. В.","","9");
INSERT INTO `persons` VALUES ("431","Шелюков Ф. С.","","9");
INSERT INTO `persons` VALUES ("432","Шершед А.","","9");
INSERT INTO `persons` VALUES ("433","Шехирин С. И.","","9");
INSERT INTO `persons` VALUES ("434","Шехирина Н. И.","","9");
INSERT INTO `persons` VALUES ("435","Шипилин","","9");
INSERT INTO `persons` VALUES ("436","Ширипин М. Е.","","9");
INSERT INTO `persons` VALUES ("437","Шихалев Ф. М.","","9");
INSERT INTO `persons` VALUES ("438","Шишов А. Н.","","9");
INSERT INTO `persons` VALUES ("439","Шишов Е. Н.","","9");
INSERT INTO `persons` VALUES ("440","Шкурбало В. М.","","9");
INSERT INTO `persons` VALUES ("441","Шмейс","","9");
INSERT INTO `persons` VALUES ("442","Шмидт Я. К.","","9");
INSERT INTO `persons` VALUES ("443","Штейнзат Е. С.","","9");
INSERT INTO `persons` VALUES ("444","Шубников","","9");
INSERT INTO `persons` VALUES ("445","Щелкунов","","9");
INSERT INTO `persons` VALUES ("446","Эльснер","","9");
INSERT INTO `persons` VALUES ("447","Эркко Ю. Ю.","","9");
INSERT INTO `persons` VALUES ("448","Ягор Ж. К.","","9");
INSERT INTO `persons` VALUES ("449","Ярышев","","9");
INSERT INTO `persons` VALUES ("450","Яскунов С. М.","","9");
INSERT INTO `persons` VALUES ("451","Ястребов А.","","9");
INSERT INTO `persons` VALUES ("452","Ятцеров П. Г.","","9");